// Model-backed DOM simulation: verifies handlers and repeated editing without browser codecs.
// This does not qualify MediaRecorder, file://, visual layout, or corporate Edge.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let confirmations=[],logs=[];
class Element {
 constructor(tag='div'){this.tagName=tag;this.children=[];this.value='';this.files=[];this.dataset={};this.listeners={};this.width=1920;this.height=1080;this.readyState=4;this.duration=12;this.videoWidth=1280;this.videoHeight=720;this.paused=true;this._time=0;this.hidden=false;this.disabled=false;this.textContent='';}
 append(...e){this.children.push(...e)}replaceChildren(...e){this.children=[...e]}setAttribute(k,v){this[k]=v}removeAttribute(k){delete this[k]}focus(){}select(){}click(){this.onclick?.()}load(){queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}get currentTime(){return this._time}set currentTime(t){this._time=t;queueMicrotask(()=>this.emit('seeked'))}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn)}removeEventListener(name,fn){this.listeners[name]=(this.listeners[name]??[]).filter(f=>f!==fn)}emit(name){for(const f of [...(this.listeners[name]??[])])f();this['on'+name]?.()}
 set src(s){this._src=s;queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}get src(){return this._src}
 getContext(){return {measureText:s=>({width:s.length*20}),drawImage(){},fillRect(){},strokeRect(){},fillText(){},save(){},restore(){}}}
 toBlob(fn){setTimeout(()=>fn(new Blob(['synthetic'])),1)}
}
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8'),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]),elements={};
for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=new Element();
elements.quality.value='1080';elements.format.value='auto';elements.target.value='60';elements.timeline.value='0';
const nav=[1,2,3,4].map(n=>{const e=new Element('button');e.dataset.step=String(n);return e}),nudges=[];
const document={getElementById:id=>elements[id],createElement:tag=>new Element(tag),querySelectorAll:s=>s==='[data-step]'?nav:nudges,fonts:{ready:Promise.resolve()},addEventListener(){},hidden:false};
class AC {constructor(){this.state='running';this.sampleRate=44100;this.currentTime=0;this.destination={}}resume(){return Promise.resolve()}decodeAudioData(){return Promise.resolve({duration:2})}close(){}createBufferSource(){return {connect(){},start(){},stop(){}}}}
const sandbox={document,window:{AudioContext:AC,addEventListener(){}},navigator:{clipboard:{writeText:async()=>{throw Error('unavailable')}}},confirm:()=>confirmations.length?confirmations.shift():true,URL:{createObjectURL:()=> 'blob:synthetic-'+Math.random(),revokeObjectURL(){}},Blob,TextDecoder,Map,Set,console,queueMicrotask,setTimeout,clearTimeout,requestAnimationFrame:()=>0,cancelAnimationFrame(){},module:{exports:{}}};
vm.createContext(sandbox);scripts.forEach(s=>vm.runInContext(s,sandbox));
const E=elements, proposal=()=>({schemaVersion:1,title:'合成',scenes:[{id:'s001',sourceIn:0,sourceOut:6,narration:'説明1',caption:'字幕1',captionPosition:'bottom',regionId:'',effect:'none'},{id:'s002',sourceIn:6,sourceOut:12,narration:'説明2',caption:'字幕2',captionPosition:'bottom',regionId:'',effect:'none'}],questions:[]});
const bodyText=e=>e.textContent+' '+e.children.map(bodyText).join(' ');
async function file(id,files){E[id].files=files;await E[id].onchange()}
function wav(name){const a=new Uint8Array(44);a.set(Buffer.from('RIFF'));a.set(Buffer.from('WAVE'),8);return {name,arrayBuffer:async()=>a.buffer}}
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name)}
(async()=>{
 await test('録画読込と同じ入力の再選択',async()=>{const f={name:'synthetic.mp4',size:100,lastModified:0};await file('sourceFile',[f]);assert.match(E.sourceInfo.textContent,/12.0秒/);assert.equal(E.sourceFile.value,'');await file('sourceFile',[f]);assert.match(E.sourceInfo.textContent,/synthetic.mp4/)});
 await test('構成JSON適用と無効JSON時の保持',async()=>{E.proposal.value=JSON.stringify(proposal());await E.applyProposal.onclick();assert.equal(E.sceneCards.children.length,2);const old=E.sceneCards.children[0];E.proposal.value='{';await E.applyProposal.onclick();assert.equal(E.sceneCards.children[0],old);assert.match(E.status.textContent,/JSON/)});
 await test('有効な再取込を取消した場合の保持',async()=>{confirmations=[false];E.proposal.value=JSON.stringify({...proposal(),title:'変更'});await E.applyProposal.onclick();assert.equal(E.title.value,'合成')});
 await test('WAVのID対応・不明音声は手動待ち',async()=>{await file('audioFiles',[wav('s001.wav'),wav('s002.wav'),wav('unknown.wav')]);assert.match(bodyText(E.audioList),/s001.wav/);assert.match(bodyText(E.pendingAudio),/unknown.wav/);assert.doesNotMatch(E.exportErrors.textContent,/WAVが未対応/)});
 await test('重複音声の置換取消と再選択',async()=>{confirmations=[false];await file('audioFiles',[wav('s001-new.wav')]);assert.doesNotMatch(bodyText(E.audioList),/s001-new.wav/);assert.equal(E.audioFiles.value,'');confirmations=[true];await file('audioFiles',[wav('s001-new.wav')]);assert.match(bodyText(E.audioList),/s001-new.wav/)});
 await test('ナレーション変更は出力停止、取消で音声復帰',async()=>{const card=E.sceneCards.children[0],narrationLabel=card.children[3],field=narrationLabel.children[0];field.value='変更した説明';field.onchange();assert.match(E.exportErrors.textContent,/再生成または内容確認/);E.undo.onclick();assert.doesNotMatch(E.exportErrors.textContent,/再生成または内容確認/)});
 await test('不正区間拒否と既存案保持',async()=>{const card=E.sceneCards.children[0],row=card.children[1],out=row.children[1].children[0];out.value=99;out.onchange();assert.match(E.status.textContent,/動画長を超え/);assert.equal(E.sceneCards.children[0].children[1].children[1].children[0].value,6)});
 await test('並べ替えでもID音声を保持・取消',async()=>{E.sceneCards.children[0].children[0].children[3].onclick();assert.equal(E.sceneCards.children[0].children[0].children[0].textContent,'s002');assert.match(bodyText(E.audioList),/s001-new.wav/);E.undo.onclick();assert.equal(E.sceneCards.children[0].children[0].children[0].textContent,'s001')});
 await test('場面削除と取消で音声も復帰',async()=>{confirmations=[true];E.sceneCards.children[0].children[0].children[4].onclick();assert.equal(E.sceneCards.children.length,1);E.undo.onclick();assert.equal(E.sceneCards.children.length,2);assert.match(bodyText(E.audioList),/s001-new.wav/)});
 await test('再取込で字幕変更しても音声を維持',async()=>{const p=proposal();p.scenes[0].caption='字幕変更';E.proposal.value=JSON.stringify(p);await E.applyProposal.onclick();assert.match(bodyText(E.audioList),/s001-new.wav/);assert.doesNotMatch(E.exportErrors.textContent,/再生成または内容確認/)});
 await test('代表画像生成の取消・再実行',async()=>{const run=E.storyboard.onclick();E.cancel.onclick();await run;assert.equal(E.downloads.children.length,0);await E.storyboard.onclick();assert.equal(E.downloads.children.length,1);assert.equal(E.sceneCards.children.length,2)});
 await test('コピー不可は手動選択に誘導',async()=>{await E.copyPrompt.onclick();assert.match(E.status.textContent,/手動でコピー/)});
 await test('保存データの再取込・素材と音声の再選択',async()=>{const p={...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1280,height:720,fps:30},regions:[],credits:'合成音'};p.scenes=p.scenes.map(s=>({...s,audioFile:s.id+'.wav',audioTextAtImport:s.narration}));await file('projectFile',[{text:async()=>JSON.stringify(p)}]);assert.match(E.exportErrors.textContent,/録画ファイルを再選択/);assert.equal(E.preview.width,1280);await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);await file('audioFiles',[wav('s001.wav'),wav('s002.wav')]);assert.equal(E.exportErrors.textContent,'素材の準備ができました。短い書き出しで再生と同期を確認してください。')});
 await test('保存前の音声本文との差は復元後も出力を止める',async()=>{const p={...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1280,height:720,fps:30},regions:[],credits:'合成音'};p.scenes=p.scenes.map(s=>({...s,audioFile:s.id+'.wav',audioTextAtImport:'過去の本文'}));await file('projectFile',[{text:async()=>JSON.stringify(p)}]);await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);await file('audioFiles',[wav('s001.wav'),wav('s002.wav')]);assert.match(E.exportErrors.textContent,/再生成または内容確認/)});
 await test('録画差替えを取消した場合の旧録画維持',async()=>{confirmations=[false];await file('sourceFile',[{name:'replacement.mp4',size:200,lastModified:1}]);assert.match(E.sourceInfo.textContent,/synthetic.mp4/);assert.doesNotMatch(E.sourceInfo.textContent,/replacement/)});
 await test('素材読み込みの取消後も編集データを維持',async()=>{const old=E.title.value;const run=file('sourceFile',[{name:'replacement.mp4',size:200,lastModified:1}]);E.cancel.onclick();await run;assert.equal(E.title.value,old);assert.match(E.sourceInfo.textContent,/synthetic.mp4/)});
 await test('復元後の手動WAV対応でも旧本文の状態を保持',async()=>{const p={...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1280,height:720,fps:30},regions:[],credits:'合成音'};p.scenes=p.scenes.map(s=>({...s,audioFile:'voice_'+s.id+'.wav',audioTextAtImport:'古い本文',audioAssigned:true}));await file('projectFile',[{text:async()=>JSON.stringify(p)}]);await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);await file('audioFiles',[wav('voice.wav')]);const row=E.pendingAudio.children[0];row.children[1].value='s001';row.children[2].onclick();assert.match(E.exportErrors.textContent,/s001：ナレーション音声の再生成または内容確認/)});
 await test('音声未割当の保存データでは新WAVを古いと誤判定しない',async()=>{const p={...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1280,height:720,fps:30},regions:[],credits:'合成音'};p.scenes=p.scenes.map(s=>({...s,audioFile:s.id+'.wav',audioTextAtImport:''}));await file('projectFile',[{text:async()=>JSON.stringify(p)}]);await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);await file('audioFiles',[wav('s001.wav'),wav('s002.wav')]);assert.doesNotMatch(E.exportErrors.textContent,/再生成または内容確認/)});
 await test('録画確認ボタンは通知後も残り同じ素材再選択で確認を省略しない',async()=>{const f={name:'replacement.mp4',size:200,lastModified:1};await file('sourceFile',[f]);assert.equal(E.confirmSource.hidden,false);E.proposal.value='{';await E.applyProposal.onclick();assert.equal(E.confirmSource.hidden,false);await file('sourceFile',[f]);assert.equal(E.confirmSource.hidden,false);E.confirmSource.onclick();assert.equal(E.confirmSource.hidden,true)});
 await test('クレジットの2行超過は書き出し前に検知',async()=>{E.credits.value='あ'.repeat(200);E.credits.onchange();assert.match(E.exportErrors.textContent,/クレジットが2行に収まりません/);E.credits.value='合成音';E.credits.onchange()});
 await test('有効な本文編集でカード入力DOMを破棄しない',async()=>{const card=E.sceneCards.children[0],field=card.children[3].children[0];field.value='変更';field.onchange();assert.equal(E.sceneCards.children[0],card);assert.equal(card.children[3].children[0],field)});
 console.log(count+' editor handler tests passed. Simulated DOM/media only; real browser acceptance not tested.');
})().catch(e=>{console.error(e);process.exitCode=1});
