// Deterministic API simulation for cancellation/cleanup races. No browser codecs are qualified.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
 const state={scheduled:[],recorders:[],tracks:[],frames:[],drawn:[],clock:0,resumeGate:null,streamError:false,rejectSource:false};
 class E {
  constructor(){this.children=[];this.dataset={};this.value='';this.files=[];this.listeners={};this.width=1920;this.height=1080;this.readyState=4;this.duration=12;this.videoWidth=1280;this.videoHeight=720;this.paused=true;this._time=0}
  append(...es){this.children.push(...es)}replaceChildren(...es){this.children=[...es]}setAttribute(k,v){this[k]=v}removeAttribute(k){delete this[k]}focus(){}select(){}click(){this.onclick?.()}load(){queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f)}removeEventListener(k,f){this.listeners[k]=(this.listeners[k]??[]).filter(v=>v!==f)}emit(k){for(const f of [...(this.listeners[k]??[])])f();this['on'+k]?.()}
  set src(s){this._src=s;queueMicrotask(()=>{if(state.rejectSource){this.emit('error');return}this.emit('loadedmetadata');this.emit('loadeddata')})}get src(){return this._src}set currentTime(v){this._time=v;queueMicrotask(()=>this.emit('seeked'))}get currentTime(){return this._time}
  getContext(){return {measureText:s=>({width:s.length*20}),drawImage(v){if(v.src)state.drawn.push(v.currentTime)},fillRect(){},strokeRect(){},fillText(){},save(){},restore(){}}}
  captureStream(){if(state.streamError)throw Error('captureStream failed');const t={kind:'video',stopped:false,stop(){this.stopped=true}};state.tracks.push(t);return new Stream([t])}
 }
 class Stream {constructor(tracks){this.tracks=tracks}getTracks(){return this.tracks}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video')}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio')}}
 class AC {constructor(){this.state='running';this.destination={}}get currentTime(){return state.clock}resume(){return state.resumeGate??Promise.resolve()}decodeAudioData(){return Promise.resolve({duration:2})}close(){}createBufferSource(){const n={connect(){},start(...args){this.startArgs=args;state.scheduled.push(this)},stop(){this.stopped=true}};return n}createMediaStreamDestination(){const t={kind:'audio',stopped:false,stop(){this.stopped=true}};state.tracks.push(t);return {stream:new Stream([t]),disconnect(){}}}}
 class Recorder {constructor(stream,options){this.state='inactive';this.mimeType=options.mimeType;state.recorders.push(this)}static isTypeSupported(){return true}start(){this.state='recording';this.started=true}stop(){this.state='inactive';queueMicrotask(()=>this.onstop?.())}}
 const els={};for(const m of html.matchAll(/id="([^"]+)"/g))els[m[1]]=new E();
 els.quality.value='1080';els.format.value='auto';els.target.value='60';els.timeline.value='0';
 const listeners={};const doc={getElementById:id=>els[id],createElement:()=>new E(),querySelectorAll:()=>[],fonts:{ready:Promise.resolve()},addEventListener:(k,f)=>listeners[k]=f,hidden:false};
 const sandbox={document:doc,window:{AudioContext:AC,MediaRecorder:Recorder,addEventListener(){}},navigator:{},confirm:()=>true,URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){}},Blob,TextDecoder,MediaStream:Stream,MediaRecorder:Recorder,HTMLCanvasElement:E,console,queueMicrotask,setTimeout,clearTimeout,requestAnimationFrame:f=>{state.frames.push(f);return state.frames.length},cancelAnimationFrame(){},module:{exports:{}}};
 vm.createContext(sandbox);scripts.forEach(s=>vm.runInContext(s,sandbox));
 async function file(id,files){els[id].files=files;await els[id].onchange()}
 async function ready(){await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);els.proposal.value=JSON.stringify({schemaVersion:1,title:'試験',scenes:[{id:'s001',sourceIn:0,sourceOut:6,narration:'説明1',caption:'要点1',captionPosition:'bottom',regionId:'',effect:'none'},{id:'s002',sourceIn:6,sourceOut:12,narration:'説明2',caption:'要点2',captionPosition:'bottom',regionId:'',effect:'none'}],questions:[]});await els.applyProposal.onclick();const bytes=new Uint8Array(44);bytes.set(Buffer.from('RIFF'));bytes.set(Buffer.from('WAVE'),8);await file('audioFiles',['s001','s002'].map(id=>({name:id+'.wav',arrayBuffer:async()=>bytes.buffer})));els.credits.value='合成音';els.credits.onchange()}
 return {state,els,ready,tick,doc,listeners,file};
}
(async()=>{
 let count=0;
 const run=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
 await run('準備中のプレビュー取消後に音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.play.onclick();await tick();f.els.cancel.onclick();resume();await tick();await tick();const scheduled=f.state.scheduled.length;f.els.cancel.onclick();await pending;assert.equal(scheduled,0)});
 await run('ストリーム初期化失敗でも編集ロックを解除',async()=>{const f=fixture();await f.ready();f.state.streamError=true;let error;try{await f.els.export.onclick()}catch(e){error=e}assert.equal(error,undefined);assert.equal(f.els.editable.disabled,false);assert.match(f.els.status.textContent,/captureStream failed/)});
 await run('合成デモの初期化失敗でも旧編集データとロック状態を維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value;f.state.streamError=true;await f.els.demo.onclick();assert.equal(f.els.editable.disabled,false);assert.equal(f.els.title.value,title);assert.match(f.els.status.textContent,/captureStream failed/)});
 await run('準備中の書き出し取消で記録・音声を開始せずトラック解放',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.export.onclick();await tick();f.els.cancel.onclick();resume();await pending;assert.equal(f.state.scheduled.length,0);assert.equal(f.state.recorders[0].started,undefined);assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.els.editable.disabled,false);assert.equal(f.els.exportResult.children.length,0)});
 await run('再生・取消を反復して二重音声を残さない',async()=>{const f=fixture();await f.ready();for(let i=0;i<3;i++){const pending=f.els.play.onclick();await tick();await tick();assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,2);f.els.cancel.onclick();await pending;assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)}});
 await run('書き出し・取消・再実行で部分動画を保存しない',async()=>{const f=fixture();await f.ready();for(let i=0;i<3;i++){const pending=f.els.export.onclick();await tick();await tick();assert.equal(f.state.recorders.at(-1).started,true);f.els.cancel.onclick();await pending;assert.equal(f.els.exportResult.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0);assert.equal(f.els.editable.disabled,false)}});
 await run('エンコーダーエラーで直ちに音声停止・トラック解放',async()=>{const f=fixture();await f.ready();const pending=f.els.export.onclick();await tick();await tick();f.state.recorders.at(-1).onerror({error:{message:'synthetic encoder error'}});await pending;assert.ok(f.state.scheduled.every(n=>n.stopped));assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.els.exportResult.children.length,0);assert.match(f.els.status.textContent,/synthetic encoder error/)});
 await run('タブ非表示で書き出し中断・編集データ維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value,pending=f.els.export.onclick();await tick();await tick();f.doc.hidden=true;f.listeners.visibilitychange();await pending;assert.ok(f.state.scheduled.every(n=>n.stopped));assert.equal(f.els.title.value,title);assert.equal(f.els.exportResult.children.length,0)});
 await run('動画デコード失敗の差替えで旧素材・構成を維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value,source=f.els.sourceInfo.textContent;f.state.rejectSource=true;await f.file('sourceFile',[{name:'broken.mp4',size:500,lastModified:1}]);assert.equal(f.els.title.value,title);assert.equal(f.els.sourceInfo.textContent,source);assert.equal(f.els.editable.disabled,false)});
 await run('場面区間外のフレームは描画へ取り込まない',async()=>{const f=fixture();await f.ready();f.state.drawn=[];const pending=f.els.play.onclick();await tick();await tick();assert.deepEqual(f.state.scheduled.map(n=>n.startArgs[0]),[.15,6.15]);f.state.clock=5.99;f.els.sourceVideo.currentTime=6.1;await f.state.frames.shift()();assert.ok(f.state.drawn.every(t=>t>=0&&t<6));assert.equal(f.els.sourceVideo.paused,true);f.els.cancel.onclick();await pending});
 await run('試聴の音声準備待ちで新規作成しても後から音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.audioList.children[0].children[2].onclick();await tick();f.els.newProject.onclick();resume();await pending;await tick();assert.equal(f.state.scheduled.length,0);assert.equal(f.els.title.value,'新しい紹介動画');assert.equal(f.els.sourceWorkspace.hidden,true)});
 await run('試聴の音声準備待ちで工程を戻しても後から音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.audioList.children[0].children[2].onclick();await tick();f.els.editSource.onclick();resume();await pending;await tick();assert.equal(f.state.scheduled.length,0)});
 await run('試聴を連打しても最後の音声だけ開始する',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const first=f.els.audioList.children[0].children[2].onclick(),second=f.els.audioList.children[1].children[2].onclick();resume();await Promise.all([first,second]);await tick();assert.equal(f.state.scheduled.length,1);f.els.newProject.onclick();assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)});
 console.log(count+' simulated media controller tests passed; browser acceptance remains unverified.');
})().catch(e=>{console.error(e);process.exitCode=1});
