// Deterministic API simulation for cancellation/cleanup races. No browser codecs are qualified.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
 const state={scheduled:[],recorders:[],tracks:[],frames:[],drawn:[],videos:[],clock:0,resumeGate:null,streamError:false,rejectSource:false,probeFail:false,probeDecodeFail:false,startFail:false,securityFail:false,probeDelay:null,demoClock:0,downloads:[],fills:[]};
 class E {
  constructor(tag='div'){this.tagName=tag;this.children=[];this.dataset={};this.value='';this.files=[];this.listeners={};this.width=1920;this.height=1080;this.readyState=4;this.duration=12;this.videoWidth=1280;this.videoHeight=720;this.paused=true;this._time=0;if(tag==='video')state.videos.push(this)}
  append(...es){this.children.push(...es)}replaceChildren(...es){this.children=[...es]}setAttribute(k,v){this[k]=v}removeAttribute(k){delete this[k]}focus(){}select(){}click(){if(this.tagName==='a')state.downloads.push(this);return this.onclick?.()}load(){queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}pause(){this.paused=true}play(){this.paused=false;if(this._src?.startsWith('blob:probe'))this._time=.1;return Promise.resolve()}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f)}removeEventListener(k,f){this.listeners[k]=(this.listeners[k]??[]).filter(v=>v!==f)}emit(k){for(const f of [...(this.listeners[k]??[])])f();this['on'+k]?.()}
  set src(s){this._src=s;queueMicrotask(()=>{if(state.rejectSource||(state.probeDecodeFail&&s.startsWith('blob:probe')&&s.includes('mp4'))){this.emit('error');return}this.emit('loadedmetadata');this.emit('loadeddata')})}get src(){return this._src}set currentTime(v){this._time=v;queueMicrotask(()=>this.emit('seeked'))}get currentTime(){return this._time}
  getContext(){return {measureText:s=>({width:s.length*20}),drawImage(v){if(v.src)state.drawn.push(v.currentTime)},fillRect(...args){state.fills.push({args,fill:this.fillStyle})},strokeRect(){},fillText(){},save(){},restore(){}}}
  captureStream(){if(state.streamError)throw Error('captureStream failed');const t={kind:'video',probe:this!==els.preview,stopped:false,stop(){this.stopped=true}};state.tracks.push(t);return new Stream([t])}
 }
 class Stream {constructor(tracks){this.tracks=tracks}getTracks(){return this.tracks}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video')}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio')}}
 class AC {constructor(){this.state='running';this.sampleRate=8000;this.destination={}}get currentTime(){return state.clock}resume(){return state.resumeGate??Promise.resolve()}decodeAudioData(){return Promise.resolve({duration:2})}close(){}createBuffer(channels,length,rate){const data=new Float32Array(length);return {duration:length/rate,sampleRate:rate,getChannelData:()=>data}}createOscillator(){return {frequency:{value:0},connect(){},start(){},stop(){},disconnect(){}}}createBufferSource(){const n={connect(){},start(...args){this.startArgs=args;state.scheduled.push(this)},stop(){this.stopped=true}};return n}createMediaStreamDestination(){const t={kind:'audio',stopped:false,stop(){this.stopped=true}};state.tracks.push(t);return {stream:new Stream([t]),disconnect(){}}}}
 class Recorder {constructor(stream,options){this.state='inactive';this.stream=stream;this.mimeType=options.mimeType;this.probe=stream.getTracks().some(t=>t.probe);state.recorders.push(this)}static isTypeSupported(){return true}start(timeslice){if(timeslice)this.probe=false;if((this.probe&&state.probeFail&&(state.probeFail==='all'||this.mimeType.includes('mp4')))||(!this.probe&&state.startFail&&this.mimeType.includes('mp4'))){const e=Error('synthetic start failure');if(state.securityFail)e.name='SecurityError';throw e}this.state='recording';this.started=true}stop(){this.state='inactive';queueMicrotask(()=>{if(this.probe)this.ondataavailable?.({data:new Blob(['probe'])});this.onstop?.()})}}
 const els={};for(const m of html.matchAll(/id="([^"]+)"/g))els[m[1]]=new E();
 els.quality.value='1080';els.format.value='auto';els.target.value='60';els.timeline.value='0';
 const listeners={};const doc={getElementById:id=>els[id],createElement:tag=>new E(tag),querySelectorAll:()=>[],fonts:{ready:Promise.resolve()},addEventListener:(k,f)=>listeners[k]=f,hidden:false};
 const sandbox={document:doc,window:{AudioContext:AC,MediaRecorder:Recorder,addEventListener(){}},navigator:{},confirm:()=>true,URL:{createObjectURL:blob=>blob instanceof Blob&&blob.size===5?'blob:probe:'+blob.type:'blob:synthetic',revokeObjectURL(){}},Blob,File:require('node:buffer').File,performance:{now:()=>state.demoClock},TextDecoder,MediaStream:Stream,MediaRecorder:Recorder,HTMLCanvasElement:E,console,queueMicrotask,setTimeout:(fn,ms)=>ms===60000?0:ms===80&&state.probeDelay?(state.probeDelay(fn),0):ms===80||ms===100?(queueMicrotask(fn),0):setTimeout(fn,ms),clearTimeout,requestAnimationFrame:f=>{state.frames.push(f);return state.frames.length},cancelAnimationFrame(){},module:{exports:{}}};
 vm.createContext(sandbox);scripts.forEach(s=>vm.runInContext(s,sandbox));
 async function file(id,files){els[id].files=files;await els[id].onchange()}
 async function ready(){await file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);els.proposal.value=JSON.stringify({schemaVersion:1,title:'試験',scenes:[{id:'s001',sourceIn:0,sourceOut:6,narration:'説明1',caption:'要点1',captionPosition:'bottom',regionId:'',effect:'none'},{id:'s002',sourceIn:6,sourceOut:12,narration:'説明2',caption:'要点2',captionPosition:'bottom',regionId:'',effect:'none'}],questions:[]});await els.applyProposal.onclick();const bytes=new Uint8Array(44);bytes.set(Buffer.from('RIFF'));bytes.set(Buffer.from('WAVE'),8);await file('audioFiles',['s001','s002'].map(id=>({name:id+'.wav',arrayBuffer:async()=>bytes.buffer})));els.credits.value='合成音';els.credits.onchange()}
 return {state,els,ready,tick,doc,listeners,file,Recorder};
}
(async()=>{
 let count=0;
 const run=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
 await run('準備中のプレビュー取消後に音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.play.onclick();await tick();f.els.cancel.onclick();resume();await tick();await tick();const scheduled=f.state.scheduled.length;f.els.cancel.onclick();await pending;assert.equal(scheduled,0)});
 await run('ストリーム初期化失敗でも編集ロックを解除',async()=>{const f=fixture();await f.ready();f.state.streamError=true;let error;try{await f.els.export.onclick()}catch(e){error=e}assert.equal(error,undefined);assert.equal(f.els.editable.disabled,false);assert.match(f.els.status.textContent,/captureStream failed/)});
 await run('合成デモの初期化失敗でも旧編集データとロック状態を維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value;f.state.streamError=true;await f.els.demo.onclick();assert.equal(f.els.editable.disabled,false);assert.equal(f.els.title.value,title);assert.match(f.els.status.textContent,/captureStream failed/)});
 await run('準備中の書き出し取消で記録・音声を開始せずトラック解放',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.export.onclick();await tick();f.els.cancel.onclick();resume();await pending;assert.equal(f.state.scheduled.length,0);assert.ok(f.state.recorders.filter(r=>!r.probe).every(r=>!r.started));assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.els.editable.disabled,false);assert.equal(f.els.exportResult.children.length,0)});
 await run('再生・取消を反復して二重音声を残さない',async()=>{const f=fixture();await f.ready();for(let i=0;i<3;i++){const pending=f.els.play.onclick();await tick();await tick();assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,2);f.els.cancel.onclick();await pending;assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)}});
 await run('書き出し・取消・再実行で部分動画を保存しない',async()=>{const f=fixture();await f.ready();for(let i=0;i<3;i++){const pending=f.els.export.onclick();await tick();await tick();assert.equal(f.state.recorders.at(-1).started,true);f.els.cancel.onclick();await pending;assert.equal(f.els.exportResult.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0);assert.equal(f.els.editable.disabled,false)}});
 await run('WebMエンコーダーエラーで直ちに音声停止・トラック解放',async()=>{const f=fixture();await f.ready();f.els.format.value='webm';const pending=f.els.export.onclick();await tick();await tick();f.state.recorders.at(-1).onerror({error:{message:'synthetic encoder error'}});await pending;assert.ok(f.state.scheduled.every(n=>n.stopped));assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.els.exportResult.children.length,0);assert.match(f.els.status.textContent,/synthetic encoder error/)});
 await run('タブ非表示で書き出し中断・編集データ維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value,pending=f.els.export.onclick();await tick();await tick();f.doc.hidden=true;f.listeners.visibilitychange();await pending;assert.ok(f.state.scheduled.every(n=>n.stopped));assert.equal(f.els.title.value,title);assert.equal(f.els.exportResult.children.length,0)});
 await run('動画デコード失敗の差替えで旧素材・構成を維持',async()=>{const f=fixture();await f.ready();const title=f.els.title.value,source=f.els.sourceInfo.textContent;f.state.rejectSource=true;await f.file('sourceFile',[{name:'broken.mp4',size:500,lastModified:1}]);assert.equal(f.els.title.value,title);assert.equal(f.els.sourceInfo.textContent,source);assert.equal(f.els.editable.disabled,false)});
 await run('場面区間外のフレームは描画へ取り込まない',async()=>{const f=fixture();await f.ready();f.state.drawn=[];const pending=f.els.play.onclick();await tick();await tick();assert.deepEqual(f.state.scheduled.map(n=>n.startArgs[0]),[.15,6.15]);f.state.clock=5.99;f.els.sourceVideo.currentTime=6.1;await f.state.frames.shift()();assert.ok(f.state.drawn.every(t=>t>=0&&t<6));assert.equal(f.els.sourceVideo.paused,true);f.els.cancel.onclick();await pending});
 await run('試聴の音声準備待ちで新規作成しても後から音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.audioList.children[0].children[2].onclick();await tick();f.els.newProject.onclick();resume();await pending;await tick();assert.equal(f.state.scheduled.length,0);assert.equal(f.els.title.value,'新しい紹介動画');assert.equal(f.els.sourceWorkspace.hidden,true)});
 await run('試聴の音声準備待ちで工程を戻しても後から音声を開始しない',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.els.audioList.children[0].children[2].onclick();await tick();f.els.editSource.onclick();resume();await pending;await tick();assert.equal(f.state.scheduled.length,0)});
 await run('試聴を連打しても最後の音声だけ開始する',async()=>{const f=fixture();await f.ready();let resume;f.state.resumeGate=new Promise(r=>resume=r);const first=f.els.audioList.children[0].children[2].onclick(),second=f.els.audioList.children[1].children[2].onclick();resume();await Promise.all([first,second]);await tick();assert.equal(f.state.scheduled.length,1);f.els.newProject.onclick();assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)});
 await run('出力形式を変えると旧動画を無効化して再生成へ戻す',async()=>{const f=fixture();await f.ready();f.els.sceneCards.children[1].children[0].children[4].onclick();f.els.nextStep.onclick();f.els.nextStep.onclick();f.els.nextStep.onclick();await tick();const pending=f.els.export.onclick();await tick();await tick();const rec=f.state.recorders.at(-1);assert.equal(rec.started,true);rec.ondataavailable({data:new Blob(['synthetic encoded video'])});f.state.clock=6;f.els.sourceVideo.currentTime=5.99;await f.state.frames.shift()();await pending;assert.match(f.els.exportResult.children[1].download,/\.mp4$/);assert.equal(f.els.guideAction.textContent,'もう一度ダウンロード');f.els.format.value='webm';f.els.format.onchange();assert.equal(f.els.exportResult.children.length,0);assert.equal(f.els.guideAction.textContent,'動画を作成してダウンロード');assert.match(f.els.outputSettingsSummary.textContent,/WebM/);assert.equal(f.els.guideAction.disabled,false)});
 await run('短い音声付き実録と映像再生を通してから本番記録を始める',async()=>{const f=fixture();await f.ready();const pending=f.els.export.onclick();await tick();await tick();const probe=f.state.recorders.find(r=>r.probe),actual=f.state.recorders.find(r=>!r.probe);assert.equal(probe.started,true);assert.ok(probe.stream.getAudioTracks().length);assert.ok(probe.stream.getVideoTracks().length);assert.ok(probe.stream.getTracks().every(t=>t.stopped));assert.equal(actual.started,true);f.els.cancel.onclick();await pending});
 await run('MP4の短時間記録開始に失敗したら実録できるWebMを選ぶ',async()=>{const f=fixture();await f.ready();f.state.probeFail=true;const pending=f.els.export.onclick();await tick();await tick();const actual=f.state.recorders.filter(r=>!r.probe);assert.equal(actual.length,1);assert.match(actual[0].mimeType,/webm/);assert.ok(f.state.recorders.filter(r=>r.probe).every(r=>r.stream.getTracks().every(t=>t.stopped)));f.els.cancel.onclick();await pending});
 await run('MP4試験動画のデコード失敗でもWebMを実録確認する',async()=>{const f=fixture();await f.ready();f.state.probeDecodeFail=true;const pending=f.els.export.onclick();await tick();await tick();assert.match(f.state.recorders.filter(r=>!r.probe)[0].mimeType,/webm/);f.els.cancel.onclick();await pending});
 await run('MP4の本番start失敗を破棄してWebMを先頭から記録する',async()=>{const f=fixture();await f.ready();f.state.startFail=true;const pending=f.els.export.onclick();await tick();await tick();const actual=f.state.recorders.filter(r=>!r.probe);assert.equal(actual.length,2);assert.match(actual[0].mimeType,/mp4/);assert.match(actual[1].mimeType,/webm/);assert.equal(actual[1].started,true);assert.ok(actual[0].stream.getTracks().every(t=>t.stopped));assert.equal(f.els.exportResult.children.length,0);f.els.cancel.onclick();await pending});
 await run('MP4実行中のエラー後はWebMだけ保存し音声を二重にしない',async()=>{const f=fixture();await f.ready();f.els.sceneCards.children[1].children[0].children[4].onclick();const pending=f.els.export.onclick();await tick();await tick();const first=f.state.recorders.filter(r=>!r.probe)[0];first.onerror({error:Error('MP4 runtime error')});await tick();await tick();const next=f.state.recorders.filter(r=>!r.probe)[1];assert.match(next.mimeType,/webm/);assert.ok(first.stream.getTracks().every(t=>t.stopped));assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,1);next.ondataavailable({data:new Blob(['synthetic output'])});f.state.clock=6;f.els.sourceVideo.currentTime=5.99;await f.state.frames.at(-1)();await pending;assert.match(f.els.exportResult.children[1].download,/\.webm$/);assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('形式試験がすべて失敗したら本番記録を始めず編集を保持する',async()=>{const f=fixture();await f.ready();const title=f.els.title.value;f.state.probeFail='all';await f.els.export.onclick();assert.equal(f.state.recorders.filter(r=>!r.probe).length,0);assert.equal(f.els.exportResult.children.length,0);assert.equal(f.els.title.value,title);assert.equal(f.els.editable.disabled,false);assert.ok(f.state.tracks.every(t=>t.stopped));assert.match(f.els.status.textContent,/使える動画形式を確認できません/)});
 await run('形式試験中の取消は別形式を始めず後始末までロックする',async()=>{const f=fixture();await f.ready();let resume;f.state.probeDelay=fn=>resume=fn;const pending=f.els.export.onclick();await tick();f.els.cancel.onclick();assert.equal(f.els.editable.disabled,true);f.els.newProject.onclick();assert.notEqual(f.els.title.value,'新しい紹介動画');f.state.probeDelay=null;resume();await pending;assert.equal(f.state.recorders.length,1);assert.ok(f.state.recorders[0].probe);assert.equal(f.els.editable.disabled,false);assert.equal(f.els.exportResult.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('形式試験中の非表示は別形式へ切り替えず中断する',async()=>{const f=fixture();await f.ready();let resume;f.state.probeDelay=fn=>resume=fn;const pending=f.els.export.onclick();await tick();f.doc.hidden=true;f.listeners.visibilitychange();f.state.probeDelay=null;resume();await pending;assert.equal(f.state.recorders.length,1);assert.equal(f.els.exportResult.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped));assert.match(f.els.status.textContent,/非表示/)});
 await run('同じ画質では形式試験を再利用し画質変更後は確認し直す',async()=>{const f=fixture();await f.ready();for(let i=0;i<3;i++){if(i===2){f.els.quality.value='720';f.els.quality.onchange()}const pending=f.els.export.onclick();await tick();await tick();f.els.cancel.onclick();await pending;assert.equal(f.state.recorders.filter(r=>r.probe).length,i===2?2:1)}});
 await run('記録のアクセス拒否は形式を替えて再試行しない',async()=>{const f=fixture();await f.ready();f.state.startFail=true;f.state.securityFail=true;await f.els.export.onclick();assert.equal(f.state.recorders.filter(r=>!r.probe).length,1);assert.doesNotMatch(f.state.recorders.at(-1).mimeType,/webm/);assert.equal(f.els.exportResult.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('練習用は720pで完成工程へ進み素材の自動ダウンロードをしない',async()=>{const f=fixture();const pending=f.els.demo.onclick();await tick();await tick();const rec=f.state.recorders.filter(r=>!r.probe).at(-1);assert.ok(rec.started);rec.ondataavailable({data:new Blob(['synthetic practice'])});f.state.demoClock=12000;await f.state.frames.at(-1)();await pending;assert.equal(f.els.quality.value,'720');assert.equal(f.els.step4.hidden,false);assert.equal(f.els.sceneCards.children.length,2);assert.equal(f.els.practiceAssetLinks.children.length,3);assert.equal(f.els.practiceAssetPanel.hidden,false);assert.equal(f.state.downloads.length,0);f.els.practiceAssetLinks.children.forEach(b=>b.click());assert.equal(f.state.downloads.length,3);assert.match(f.state.downloads[0].download,/synthetic-recording/);assert.equal(f.state.downloads[1].download,'s001.wav');assert.equal(f.state.downloads[2].download,'s002.wav');f.els.practiceAssetLinks.children[0].click();assert.equal(f.state.downloads.length,4);f.els.newProject.onclick();assert.equal(f.els.practiceAssetPanel.hidden,true);assert.equal(f.els.practiceAssetLinks.children.length,0)});
 await run('練習用のMP4開始失敗ではWebMに替えて準備できる',async()=>{const f=fixture();f.state.startFail=true;const pending=f.els.demo.onclick();await tick();await tick();const actual=f.state.recorders.filter(r=>!r.probe);assert.equal(actual.length,2);assert.match(actual[1].mimeType,/webm/);actual[1].ondataavailable({data:new Blob(['synthetic practice'])});f.state.demoClock=12000;await f.state.frames.at(-1)();await pending;assert.equal(f.els.step4.hidden,false);assert.match(f.els.practiceAssetLinks.children[0].textContent,/webm/);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('練習作成の取消は次の描画を待たず終了し元の作業を保持する',async()=>{const f=fixture();await f.ready();const title=f.els.title.value;const pending=f.els.demo.onclick();await tick();await tick();f.els.cancel.onclick();await pending;assert.equal(f.els.title.value,title);assert.equal(f.els.sceneCards.children.length,2);assert.equal(f.els.practiceAssetLinks.children.length,0);assert.equal(f.els.editable.disabled,false);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('練習作成中の非表示も部分素材を残さず終了する',async()=>{const f=fixture();const pending=f.els.demo.onclick();await tick();await tick();f.doc.hidden=true;f.listeners.visibilitychange();await pending;assert.equal(f.els.practiceAssetLinks.children.length,0);assert.equal(f.els.sceneCards.children.length,0);assert.ok(f.state.tracks.every(t=>t.stopped));assert.equal(f.els.editable.disabled,false)});
 await run('練習作成でアクセス拒否が出たら形式を変えて続けない',async()=>{const f=fixture();f.state.startFail=true;f.state.securityFail=true;await f.els.demo.onclick();assert.equal(f.state.recorders.filter(r=>!r.probe).length,1);assert.equal(f.els.practiceAssetLinks.children.length,0);assert.equal(f.els.editable.disabled,false);assert.ok(f.state.tracks.every(t=>t.stopped))});
 await run('練習素材の保存ボタンは別録画への置換後に残さない',async()=>{const f=fixture();const pending=f.els.demo.onclick();await tick();await tick();f.state.recorders.filter(r=>!r.probe).at(-1).ondataavailable({data:new Blob(['synthetic practice'])});f.state.demoClock=12000;await f.state.frames.at(-1)();await pending;assert.equal(f.els.practiceAssetLinks.children.length,3);await f.file('sourceFile',[{name:'my-recording.mp4',size:400,lastModified:2}]);assert.equal(f.els.practiceAssetPanel.hidden,true);assert.equal(f.els.practiceAssetLinks.children.length,0)});
 await run('H.264指定のないMP4は候補にせずWebMで記録する',async()=>{const f=fixture();await f.ready();f.Recorder.isTypeSupported=t=>!/avc1/.test(t);const pending=f.els.export.onclick();await tick();await tick();assert.ok(f.state.recorders.length>0);assert.ok(f.state.recorders.every(r=>/webm/.test(r.mimeType)));f.els.cancel.onclick();await pending});
 await run('シーク前にフレーム通知を登録し待機時間で止まらない',async()=>{const f=fixture();await f.ready();const v=f.els.sourceVideo;let waiting=null,fired=0;Object.getPrototypeOf(v).toBlob=cb=>cb(new Blob(['png']));v.requestVideoFrameCallback=cb=>{waiting=cb;return 1};v.cancelVideoFrameCallback=()=>{waiting=null};Object.defineProperty(v,'currentTime',{configurable:true,get(){return this._time},set(t){this._time=t;const cb=waiting;waiting=null;queueMicrotask(()=>{this.emit('seeked');if(cb){fired++;cb()}})}});const started=Date.now();await f.els.storyboard.onclick();assert.equal(fired,4);assert.ok(Date.now()-started<400,'seek waited for the frame-callback timeout');assert.equal(f.els.downloads.children.length,1)});
 await run('元動画の速度・ミュート変更後も両動画を等速・無音で合成プレビューする',async()=>{
  const f=fixture();await f.ready();const source=f.els.sourceVideo,next=f.state.videos[0];
  for(const v of [source,next]){v.playbackRate=2;v.muted=false}
  const pending=f.els.play.onclick();await tick();await tick();
  for(const v of [source,next]){assert.equal(v.playbackRate,1);assert.equal(v.muted,true)}
  assert.equal(source.paused,false);f.state.clock=6.1;source.currentTime=5.99;next.currentTime=6.1;await f.state.frames.at(-1)();
  assert.equal(next.paused,false);assert.equal(next.playbackRate,1);assert.equal(next.muted,true);assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,2);
  f.els.cancel.onclick();await pending;assert.equal(f.els.sourceVideo.controls,true);assert.ok(f.state.scheduled.every(n=>n.stopped));
 });
 await run('元動画を倍速・ミュート解除しても等速に戻し同期エラーなく書き出す',async()=>{
  const f=fixture();await f.ready();const source=f.els.sourceVideo,next=f.state.videos[0];source.playbackRate=2;source.muted=false;
  const pending=f.els.export.onclick();await tick();await tick();assert.equal(source.playbackRate,1);assert.equal(source.muted,true);
  const recorder=f.state.recorders.find(r=>!r.probe);assert.ok(recorder.started);recorder.ondataavailable({data:new Blob(['synthetic output'])});
  f.state.clock=1;source.currentTime=f.state.clock*source.playbackRate;await f.state.frames.at(-1)();assert.equal(recorder.state,'recording');
  f.state.clock=6.1;source.currentTime=5.99;next.currentTime=6.1;await f.state.frames.at(-1)();assert.equal(next.playbackRate,1);assert.equal(next.muted,true);
  f.state.clock=12;next.currentTime=11.99;await f.state.frames.at(-1)();await pending;
  assert.match(f.els.exportResult.children[1].download,/\.(mp4|webm)$/);assert.doesNotMatch(f.els.status.textContent,/同期が崩れ/);assert.ok(f.state.tracks.every(t=>t.stopped));assert.ok(f.state.scheduled.every(n=>n.stopped));
 });
 await run('声なしプレビューは保持したWAVをスケジュールしない',async()=>{const f=fixture();await f.ready();f.els.useNarration.checked=false;f.els.useNarration.onchange();const pending=f.els.play.onclick();await tick();await tick();assert.equal(f.state.scheduled.length,0);f.els.cancel.onclick();await pending;assert.equal(f.els.editable.disabled,false)});
 await run('声なし書き出しは音声クロックではなく実時間で場面と終了を進める',async()=>{
  const f=fixture();await f.ready();f.els.useNarration.checked=false;f.els.useNarration.onchange();f.state.demoClock=50000;
  const pending=f.els.export.onclick();await tick();await tick();const recorder=f.state.recorders.find(r=>!r.probe);assert.ok(recorder.started);
  f.state.clock=1000;f.state.demoClock=51000;f.els.sourceVideo.currentTime=1;await f.state.frames.at(-1)();
  assert.equal(recorder.state,'recording');assert.equal(Number(f.els.timeline.value),1);assert.equal(f.state.scheduled.length,0);
  f.state.demoClock=56100;f.els.sourceVideo.currentTime=5.99;f.state.videos[0].currentTime=6.1;await f.state.frames.at(-1)();
  assert.equal(recorder.state,'recording');assert.ok(Math.abs(Number(f.els.timeline.value)-6.1)<.00001);
  recorder.ondataavailable({data:new Blob(['synthetic output'])});f.state.demoClock=62000;f.state.videos[0].currentTime=11.99;await f.state.frames.at(-1)();await pending;
  assert.match(f.els.exportResult.children[1].download,/\.(mp4|webm)$/);assert.equal(Number(f.els.timeline.value),12);assert.ok(f.state.tracks.every(t=>t.stopped));
 });
 await run('声なし途中プレビューも経過実時間を再開位置に加える',async()=>{
  const f=fixture();await f.ready();f.els.useNarration.checked=false;f.els.useNarration.onchange();f.els.timeline.value='2';f.state.demoClock=50000;
  const pending=f.els.play.onclick();await tick();await tick();f.state.clock=1000;f.state.demoClock=51000;f.els.sourceVideo.currentTime=3;await f.state.frames.at(-1)();
  assert.equal(Number(f.els.timeline.value),3);assert.equal(f.state.scheduled.length,0);f.els.cancel.onclick();await pending;assert.equal(f.els.editable.disabled,false);
 });
 console.log(count+' simulated media controller tests passed; browser acceptance remains unverified.');
})().catch(e=>{console.error(e);process.exitCode=1});
