// State/DOM model only: observers report explicit geometry, not rendered pixels.
const assert=require('node:assert/strict');
const {fixture,markup,html,tick}=require('./workflow.test.cjs');
(async()=>{
 let count=0;const test=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
 await test('案内を編集欄の直後へ移し上部だけへの依存をなくす',()=>{const f=fixture();assert.equal(f.E.guidePanel.parentElement,f.E.stageActions);assert.equal(f.E.stageActions.parentElement,f.E.workArea);assert.ok(markup.indexOf('id="guidePanel"')>markup.indexOf('id="step4"'));assert.ok(markup.indexOf('id="guidePanel"')<markup.indexOf('id="outcomePanel"'));assert.equal(f.E.quickActionBar.hidden,true);assert.equal(Boolean(f.E.stageShortcuts.open),false);assert.equal(f.E.previousStep.parentElement,f.E.guideAction.parentElement)});
 await test('画像作成より前に任意の領域編集を並べない',()=>{assert.ok(markup.indexOf('id="sourcePreparation"')<markup.indexOf('id="regionPanel"'));assert.doesNotMatch(html,/\.workspace\.has-project \.outcome-panel\{order:-1\}/)});
 await test('監視APIのない環境でも下部の主操作を利用できる',async()=>{const f=fixture();await f.source();assert.equal(f.E.guidePanel.hidden,false);assert.equal(f.E.quickActionBar.hidden,true);await f.E.guideAction.click();assert.equal(f.E.downloads.children.length,1)});
 await test('固定案内は主ボタンの表示を監視し同じラベルを使う',async()=>{const f=fixture({observers:true});assert.equal(f.state.observed,f.E.guideAction);await f.source();assert.equal(f.E.quickActionBar.hidden,false);assert.equal(f.E.quickAction.textContent,f.E.guideAction.textContent);assert.equal(f.state.styles['--action-bar-height'],'110px');f.state.observerCallback([{isIntersecting:true,intersectionRatio:1}]);assert.equal(f.E.quickActionBar.hidden,true);assert.equal(f.state.styles['--action-bar-height'],'0px');f.state.observerCallback([{isIntersecting:false,intersectionRatio:0}]);assert.equal(f.E.quickActionBar.hidden,false)});
 await test('固定ボタンにフォーカスがある間は交差判定だけで消さない',async()=>{const f=fixture({observers:true});await f.source();f.E.quickAction.focus();f.state.observerCallback([{isIntersecting:true,intersectionRatio:1}]);assert.equal(f.E.quickActionBar.hidden,false);assert.equal(f.state.activeElement,f.E.quickAction)});
 await test('背の低い画面・高すぎる案内・仮想キーボードは通常配置へ戻す',async()=>{for(const options of [{viewportHeight:560},{dockHeight:221},{viewportHeight:900,visualViewportHeight:700}]){const f=fixture({observers:true,...options});await f.source();assert.equal(f.E.quickActionBar.hidden,true);assert.equal(f.E.guidePanel.hidden,false);assert.equal(f.state.styles['--action-bar-height'],'0px')}});
 await test('文字入力中に案内を重ねず入力終了後に戻す',async()=>{const f=fixture({observers:true});await f.source();f.E.purpose.focus();assert.equal(f.E.quickActionBar.hidden,true);f.doc.activeElement=null;f.state.activeElement=null;f.state.docListeners.focusout();await new Promise(r=>setTimeout(r,1));assert.equal(f.E.quickActionBar.hidden,false)});
 await test('下部の画像作成から保存開始と次工程へ一貫して進める',async()=>{const f=fixture({observers:true});await f.source();await f.E.quickAction.click();assert.equal(f.E.downloads.children.length,1);assert.match(f.E.quickAction.textContent,/一覧PNG/);f.E.quickAction.click();assert.equal(f.state.downloads.length,1);assert.match(f.E.quickAction.textContent,/次へ/);f.E.quickAction.click();assert.deepEqual(f.active(),[2]);assert.equal(f.state.activeElement,f.E.structureHeading);assert.equal(f.state.scrolls.at(-1).element,f.E.structureHeading);assert.equal(f.state.scrolls.at(-1).options.block,'start')});
 await test('コピー待ちの繰り返し操作を止め完了文をボタンの近くへ出す',async()=>{const f=fixture({observers:true});await f.source();f.step(2);let done;f.state.clipboardGate=new Promise(r=>done=r);const pending=f.E.quickAction.click();assert.equal(f.E.quickAction.disabled,false);assert.equal(f.E.quickAction.attributes['aria-disabled'],'true');assert.equal(f.E.guideAction.attributes['aria-disabled'],'true');f.E.guideAction.click();done();await pending;assert.equal(f.E.quickAction.disabled,false);assert.match(f.E.quickFeedback.textContent,/コピーしました/);assert.equal(f.E.quickFeedback.textContent,f.E.guideFeedback.textContent);assert.equal(f.E.quickFeedback.attributes['aria-live'],'off');assert.match(f.E.quickAction.textContent,/回答を貼り付ける/)});
 await test('下部からの不正JSON読込は回答欄を開いてフォーカスする',async()=>{const f=fixture({observers:true});await f.source();f.step(2);f.E.proposal.value='{';f.E.proposal.oninput();f.E.structureIntake.open=false;await f.E.quickAction.click();assert.equal(f.E.structureIntake.open,true);assert.equal(f.state.activeElement,f.E.proposal);assert.equal(f.state.scrolls.at(-1).element,f.E.proposal);assert.match(f.E.quickFeedback.textContent,/JSON/);assert.equal(f.E.quickAction.disabled,false);assert.equal(f.E.sceneCards.children.length,0)});
 await test('閉じた回答欄と台本はコピー失敗時に開き手動選択する',async()=>{const f=fixture({observers:true});await f.source();f.step(2);f.state.clipboardFails=true;f.E.structureIntake.open=false;await f.E.quickAction.click();assert.equal(f.E.promptDetails.open,true);assert.equal(f.state.activeElement,f.E.prompt);assert.equal(f.state.scrolls.at(-1).element,f.E.prompt);assert.match(f.E.quickFeedback.textContent,/手動でコピー/)});
 await test('音声不足の動画工程から準備へ戻りWAV読込で次を切り替える',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(4);await tick();assert.equal(f.E.export.disabled,true);assert.match(f.E.quickAction.textContent,/声の準備へ戻る/);f.E.quickAction.click();assert.deepEqual(f.active(),[3]);await f.E.quickAction.click();assert.equal(f.E.quickAction.textContent,'WAVファイルを選ぶ');await f.audio();assert.equal(f.E.quickAction.textContent,'完成を確認する');f.E.quickAction.click();assert.deepEqual(f.active(),[4]);await tick();assert.equal(f.E.export.disabled,false)});
 await test('音声選択待ちの未対応WAVへスクロールできる',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(3);await f.file('audioFiles',[f.wav('unknown.wav')]);f.E.quickAction.click();assert.equal(f.state.activeElement,f.E.pendingAudio.children[0].children[1]);assert.equal(f.state.scrolls.at(-1).element,f.state.activeElement)});
 await test('台本変更後は古い音声完了を引き継がず台本コピーに戻る',async()=>{const f=fixture({observers:true});await f.source();await f.apply();await f.audio();f.step(2);const field=f.E.sceneCards.children[0].querySelector('[data-field="narration"]');field.value='新しい説明';field.onchange();f.step(3);assert.equal(f.E.quickAction.textContent,'台本をコピー');assert.equal(f.E.export.disabled,true)});
 await test('素材なしの復元でも前の録画を選ぶ操作を下部に残す',async()=>{const f=fixture({observers:true});await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);assert.equal(f.E.stageActions.hidden,false);assert.equal(f.E.quickActionBar.hidden,false);assert.equal(f.E.quickAction.textContent,'前の録画を選ぶ');assert.equal(f.E.quickAction.disabled,false)});
 await test('素材読込の途中は録画未確定でも停止が使える',async()=>{const f=fixture({observers:true});let done;f.state.resumeGate=new Promise(r=>done=r);const pending=f.source();await tick();assert.equal(f.E.quickActionBar.hidden,false);assert.equal(f.E.quickAction.hidden,true);assert.equal(f.E.quickStop.hidden,false);assert.equal(f.E.quickStop.disabled,false);assert.equal(f.E.quickStop.isEffectivelyDisabled(),false);f.E.quickStop.click();assert.equal(f.E.quickStop.attributes['aria-disabled'],'true');assert.equal(f.E.editable.disabled,true);done();await pending;assert.equal(f.E.editable.disabled,false);assert.equal(f.E.quickActionBar.hidden,true)});
 await test('下部からの処理停止は後始末まで操作ロックを保持する',async()=>{const f=fixture({observers:true});await f.source();let done;f.state.seekGate=new Promise(r=>done=r);const pending=f.E.quickAction.click();await tick();assert.equal(f.E.quickStop.hidden,false);f.E.quickStop.click();assert.equal(f.E.quickStop.attributes['aria-disabled'],'true');assert.equal(f.E.guideAction.disabled,true);assert.equal(f.E.quickAction.disabled,true);done();await pending;assert.equal(f.E.quickStop.hidden,true);assert.equal(f.E.quickAction.disabled,false);assert.equal(f.E.guideAction.disabled,false);assert.match(f.E.quickFeedback.textContent,/中止/)});
 await test('次工程へ古い結果文を持ち越さず補助欄も閉じる',async()=>{const f=fixture({observers:true});await f.source();f.step(2);await f.E.quickAction.click();assert.notEqual(f.E.quickFeedback.textContent,'');f.E.stageShortcuts.open=true;await f.apply();f.E.nextStep.click();assert.equal(f.E.quickFeedback.textContent,'');assert.equal(f.E.stageShortcuts.open,false);assert.deepEqual(f.active(),[3])});

 await test('固定欄から開いたファイル選択の後に不正WAVを読んでも結果へ戻れる',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(3);await f.E.quickAction.click();f.E.quickAction.click();await f.file('audioFiles',[{name:'invalid.wav',arrayBuffer:async()=>new Uint8Array(2).buffer}]);assert.match(f.E.quickFeedback.textContent,/RIFF/);assert.equal(f.E.quickFeedback.textContent,f.E.guideFeedback.textContent);assert.equal(f.state.activeElement,f.E.audioFeedback);assert.equal(f.state.scrolls.at(-1).element,f.E.audioFeedback);assert.equal(f.E.export.disabled,true)});
 await test('固定欄の選択後に正常WAVを読むと完了と次の操作が更新される',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(3);await f.E.quickAction.click();f.E.quickAction.click();await f.audio();assert.notEqual(f.E.quickFeedback.textContent,'');assert.equal(f.state.activeElement,f.E.audioFeedback);assert.equal(f.E.quickAction.textContent,'完成を確認する')});
 await test('ファイル選択のキャンセルは次の通常操作へ案内元を持ち越さない',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(3);await f.E.quickAction.click();f.E.quickAction.click();f.E.audioFiles.emit('cancel');await f.file('audioFiles',[{name:'invalid.wav',arrayBuffer:async()=>new Uint8Array(2).buffer}]);assert.equal(f.E.quickFeedback.textContent,'');assert.equal(f.E.guideAction.disabled,false)});
 await test('低い画面でも工程末尾の停止で処理を中止できる',async()=>{const f=fixture({observers:true,viewportHeight:560});await f.source();let done;f.state.seekGate=new Promise(r=>done=r);const pending=f.E.guideAction.click();await tick();assert.equal(f.E.quickActionBar.hidden,true);assert.equal(f.E.guideAction.hidden,true);assert.equal(f.E.guideStop.hidden,false);assert.equal(f.E.guideStop.disabled,false);assert.equal(f.E.guideStop.isEffectivelyDisabled(),false);assert.match(f.E.guideTitle.textContent,/素材を準備/);f.E.guideStop.click();assert.equal(f.E.guideStop.attributes['aria-disabled'],'true');done();await pending;assert.equal(f.E.guideStop.hidden,true);assert.equal(f.E.guideAction.hidden,false);assert.equal(f.E.guideAction.disabled,false)});
 await test('低い画面でも録画確定前の停止を工程末尾へ出す',async()=>{const f=fixture({observers:true,viewportHeight:560});let done;f.state.resumeGate=new Promise(r=>done=r);const pending=f.source();await tick();assert.equal(f.E.stageActions.hidden,false);assert.equal(f.E.guidePanel.hidden,false);assert.equal(f.E.guideStop.hidden,false);f.E.guideStop.click();done();await pending;assert.equal(f.E.stageActions.hidden,true)});
 await test('固定の主操作から停止へフォーカスを渡し完了時に戻す',async()=>{const f=fixture({observers:true});await f.source();f.E.quickAction.focus();let done;f.state.seekGate=new Promise(r=>done=r);const pending=f.E.quickAction.click();await tick();assert.equal(f.state.activeElement,f.E.quickStop);f.E.quickStop.click();done();await pending;assert.equal(f.state.activeElement,f.E.quickAction)});
 await test('高さ不足で固定欄が消えると同じ通常操作へフォーカスを移す',async()=>{const f=fixture({observers:true});await f.source();f.E.quickAction.focus();f.window.innerHeight=560;f.state.windowListeners.resize();assert.equal(f.E.quickActionBar.hidden,true);assert.equal(f.state.activeElement,f.E.guideAction);assert.equal(f.state.scrolls.at(-1).element,f.E.guideAction)});
 await test('別の通常操作の結果や編集変更へ古いコピー成功を持ち越さない',async()=>{const f=fixture({observers:true});await f.source();await f.apply();f.step(3);await f.E.quickAction.click();assert.match(f.E.quickFeedback.textContent,/コピーしました/);await f.E.copyScript.click();assert.equal(f.E.quickFeedback.textContent,'');await f.E.guideAction.click();f.step(2);const field=f.E.sceneCards.children[0].querySelector('[data-field="caption"]');field.value='字幕を修正';field.onchange();assert.equal(f.E.guideFeedback.textContent,'')});
 await test('固定欄の文を2行までにし全文と余白を通常欄へ残すCSS',()=>{assert.match(html,/-webkit-line-clamp:2/);assert.match(html,/scroll-padding-bottom:calc\(var\(--action-bar-height,0px\) \+ 24px\)/);assert.match(html,/env\(safe-area-inset-bottom\)/);assert.match(html,/class="quick-action-space"/);assert.equal(markup.match(/id="guideStop"/g).length,1)});

 await test('コピー待ちはフォーカス可能なままaria-disabledで二重実行を防ぐ',async()=>{const f=fixture({observers:true});await f.source();f.step(2);f.E.quickAction.focus();let done;f.state.clipboardGate=new Promise(r=>done=r);const pending=f.E.quickAction.click();assert.equal(f.E.quickAction.disabled,false);assert.equal(f.E.quickAction.attributes['aria-disabled'],'true');assert.equal(f.state.activeElement,f.E.quickAction);f.E.quickAction.click();done();await pending;assert.equal(f.E.quickAction.attributes['aria-disabled'],'false');assert.equal(f.state.activeElement,f.E.quickAction)});
 await test('コピー完了時に別の入力へ移動したフォーカスを奪わない',async()=>{const f=fixture({observers:true});await f.source();f.step(2);f.E.quickAction.focus();let done;f.state.clipboardGate=new Promise(r=>done=r);const pending=f.E.quickAction.click();f.E.proposal.focus();done();await pending;assert.equal(f.state.activeElement,f.E.proposal)});
 console.log(count+' navigation model tests passed; pixel layout and actual browser export are not established.');
})().catch(e=>{console.error(e.stack);process.exitCode=1});
