// Static CSS contracts only. These do not establish installed-font availability,
// actual glyph rendering, pixel layout, or absence of clipping in a real browser.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const css=html.match(/<style>([\s\S]*?)<\/style>/)[1];
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
test('BIZ UDPゴシックの公式ファミリー名と日本語名を優先しOSフォントへ代替',()=>{assert.match(css,/--ui-font:"BIZ UDPGothic","BIZ UDPゴシック","Yu Gothic","YuGothic","Meiryo","Hiragino Sans",system-ui,sans-serif/);assert.match(css,/body\{[^}]*font:18px\/1\.75 var\(--ui-font\)/)});
test('補助文字を含む明示サイズは15px以上で説明文とラベルを拡大',()=>{const sizes=[...css.matchAll(/font-size:(\d+)px/g)].map(m=>Number(m[1]));assert.ok(sizes.length>15);assert.ok(sizes.every(n=>n>=15));assert.match(css,/label\{[^}]*font-size:18px/);assert.match(css,/label span,\.hint\{font-size:16px/);assert.match(css,/#status\{[^}]*font-size:16px/);assert.match(css,/footer\{[^}]*font-size:16px/)});
test('入力・ボタンとCopilotの長文欄も同じUIフォントを継承',()=>{assert.match(css,/button,input,textarea,select\{font:inherit\}/);assert.match(css,/\.textarea-code\{font-family:var\(--ui-font\);font-size:18px;line-height:1\.75/);assert.match(css,/pre\{font-family:var\(--ui-font\);font-size:18px/);assert.doesNotMatch(css,/ui-monospace/)});
test('長い操作名とファイル名は折返しを許し固定幅からのはみ出しに備える',()=>{assert.match(css,/button,\.file-label,\.download\{min-height:46px;max-width:100%;white-space:normal;overflow-wrap:anywhere/);assert.match(css,/\.row button\{flex:0 1 auto;min-width:0\}/);assert.match(css,/#downloads a\{max-width:100%;overflow-wrap:anywhere\}/);assert.match(css,/\.asset strong,\.asset p,\.context-feedback,#status,#previewStatus\{overflow-wrap:anywhere\}/)});
test('狭い幅では工程を2列にし再生・次へ操作を縦に並べる',()=>{assert.match(css,/@media\(max-width:600px\)\{\.workflow\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/\.step-actions button\{width:100%;flex:1 1 100%\}/);assert.match(css,/#play,#playFromStart,#previewStop\{flex:1 1 100%;width:100%\}/);assert.match(css,/\.step-heading,\.subheading,\.summary-strip,\.operation-bar\{flex-wrap:wrap\}/);assert.match(html,/<option value="auto">MP4優先（WebM自動）<\/option>/);assert.match(html,/MP4が使えない場合はWebMを試します。/)});
test('操作サイズと行間を確保し小画面でも文字サイズを戻さない',()=>{assert.match(css,/input:not\(\[type=range\]\):not\(\[type=file\]\),textarea,select\{min-height:48px/);assert.match(css,/\.workflow button\{min-width:0;font-size:18px\}/);assert.match(css,/#play,#playFromStart,#previewStop\{font-size:18px\}/);assert.match(css,/\.scene-title button,\.scene-source-button\{font-size:18px\}/)});
test('フォントファイルの埋込・CDN・外部フォント取得を追加しない',()=>{assert.doesNotMatch(css,/@font-face|@import|url\s*\(/i);assert.doesNotMatch(html,/fonts\.(?:googleapis|gstatic)\.com/);assert.match(html,/font-src 'none'/);assert.match(html,/connect-src 'none'/)});
console.log(count+' static readability checks passed; actual font selection and browser layout remain unverified.');
