// Static CSS contracts only. These do not establish installed-font availability,
// actual glyph rendering, pixel layout, or absence of clipping in a real browser.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const css=html.match(/<style>([\s\S]*?)<\/style>/)[1];
const rule=selector=>{const escaped=selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const blocks=[...css.matchAll(new RegExp(escaped+'\\{([^{}]*)\\}','g'))];assert.ok(blocks.length,'missing selector '+selector);return Object.fromEntries(blocks.flatMap(m=>m[1].split(';').filter(Boolean).map(s=>{const i=s.indexOf(':');return [s.slice(0,i).trim(),s.slice(i+1).trim()]})))};
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
test('DOCTYPEを先頭に保ち初心者音声レイアウトのCSSをstyle内に置く',()=>{assert.match(html,/^<!doctype html>/i);assert.equal(rule('.handoff-stack.single-voice')['grid-template-columns'],'1fr');assert.doesNotMatch(html.slice(0,html.indexOf('<style>')),/\.handoff-stack/)});
test('BIZ UDPゴシックの公式ファミリー名と日本語名を優先しOSフォントへ代替',()=>{assert.match(css,/--ui-font:"BIZ UDPGothic","BIZ UDPゴシック","Yu Gothic","YuGothic","Meiryo","Hiragino Sans",system-ui,sans-serif/);assert.match(css,/body\{[^}]*font:18px\/1\.75 var\(--ui-font\)/)});
test('補助文字を含む明示サイズは15px以上で説明文とラベルを拡大',()=>{const sizes=[...css.matchAll(/font-size:(\d+)px/g)].map(m=>Number(m[1]));assert.ok(sizes.length>15);assert.ok(sizes.every(n=>n>=15));assert.match(css,/label\{[^}]*font-size:18px/);assert.match(css,/label span,\.hint\{font-size:16px/);assert.match(css,/#status\{[^}]*font-size:16px/);assert.match(css,/footer\{[^}]*font-size:16px/)});
test('入力・ボタンとCopilotの長文欄も同じUIフォントを継承',()=>{assert.match(css,/button,input,textarea,select\{font:inherit\}/);assert.match(css,/\.textarea-code\{font-family:var\(--ui-font\);font-size:18px;line-height:1\.75/);assert.match(css,/pre\{font-family:var\(--ui-font\);font-size:18px/);assert.doesNotMatch(css,/ui-monospace/)});
test('長い操作名とファイル名は折返しを許し固定幅からのはみ出しに備える',()=>{const controls=rule('button,.file-label,.download');assert.equal(controls['min-height'],'46px');assert.equal(controls['max-width'],'100%');assert.equal(controls['white-space'],'normal');assert.equal(controls['overflow-wrap'],'anywhere');assert.equal(rule('.row button').flex,'0 1 auto');assert.equal(rule('#downloads a')['max-width'],'100%');assert.equal(rule('#downloads a')['overflow-wrap'],'anywhere');assert.match(css,/\.asset strong,\.asset p,\.context-feedback,#status,#previewStatus\{overflow-wrap:anywhere\}/)});
test('狭い幅では工程を2列にし再生・次へ操作を縦に並べる',()=>{assert.match(css,/@media\(max-width:600px\)\{\.workflow\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/\.step-actions button\{width:100%;flex:1 1 100%\}/);assert.match(css,/#play,#playFromStart,#previewStop\{flex:1 1 100%;width:100%\}/);assert.match(css,/\.step-heading,\.subheading,\.summary-strip,\.operation-bar\{flex-wrap:wrap\}/);assert.match(html,/<option value="auto">MP4優先（WebM自動）<\/option>/);assert.match(html,/MP4が使えない場合はWebMを試します。/)});
test('操作サイズと行間を確保し小画面でも文字サイズを戻さない',()=>{assert.match(css,/input:not\(\[type=range\]\):not\(\[type=file\]\),textarea,select\{min-height:48px/);assert.equal(rule('.workflow button')['min-width'],'0');assert.equal(rule('.workflow button')['font-size'],'18px');assert.match(css,/#play,#playFromStart,#previewStop\{font-size:18px\}/);assert.match(css,/\.scene-title button,\.scene-source-button\{font-size:18px\}/)});
test('フォントファイルの埋込・CDN・外部フォント取得を追加しない',()=>{assert.doesNotMatch(css,/@font-face|@import|url\s*\(/i);assert.doesNotMatch(html,/fonts\.(?:googleapis|gstatic)\.com/);assert.match(html,/font-src 'none'/);assert.match(html,/connect-src 'none'/)});
test('主要な文字色とフォーカスを背景に対して十分な濃さに保つ',()=>{const tokens=rule(':root');const luminance=hex=>{let h=hex.replace('#','');if(h.length===3)h=[...h].map(c=>c+c).join('');const values=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return values[0]*.2126+values[1]*.7152+values[2]*.0722};const contrast=(a,b)=>{const [hi,lo]=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (hi+.05)/(lo+.05)};for(const [fg,bg] of [[tokens['--ink'],'#fff'],[tokens['--muted'],'#fff'],[tokens['--muted'],tokens['--surface-2']],[tokens['--accent'],'#fff'],['#fff',tokens['--accent']],[tokens['--danger'],'#fff'],['#edf5f8',tokens['--media']],['#c8d8e1',tokens['--media']]])assert.ok(contrast(fg,bg)>=4.5,fg+' on '+bg);assert.ok(contrast(tokens['--input-line'],'#fff')>=3);assert.ok(contrast(tokens['--focus'],'#fff')>=3);assert.ok(contrast('#99dfd3',tokens['--media'])>=3)});
test('短い画面でプレビューを固定せず警告と停止までスクロールできるCSSにする',()=>{assert.match(css,/@media\(max-height:900px\)\{\.outcome-panel\{position:static\}\}/);assert.match(css,/#outcomeMedia button:focus-visible,#outcomeMedia input:focus-visible\{outline-color:#99dfd3\}/);assert.match(css,/button\.danger:not\(:disabled\):hover,[^{]+\{[^}]*background:var\(--danger-soft\)/);assert.doesNotMatch(css,/fieldset:disabled\{opacity:\.[0-9]/);assert.match(css,/button\.danger,\.scene-title button\[aria-label\$="を削除"\]:not\(:disabled\)\{/)});
test('小画面のヘッダーと本文の端をそろえ見本の高さの上書きを解消する',()=>{assert.match(css,/@media\(max-width:800px\)\{header\{padding:18px 16px\}main\{padding:24px 16px 30px\}/);const narrow=css.indexOf('@media(max-width:430px)');assert.ok(narrow>css.indexOf('height:196px'));assert.match(css.slice(narrow),/\.example-window\{height:184px\}/);assert.doesNotMatch(css.slice(narrow),/height:196px/)});
console.log(count+' static readability checks passed; actual font selection and browser layout remain unverified.');
