// Non-browser workflow model: HTML ancestry plus deterministic DOM/media stubs.
// Does not render pixels, open a local app, or qualify real codecs and file dialogs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const markup=html.slice(0,html.indexOf('<script>')),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
 const state={confirmations:[],confirmationCount:0,downloads:[],windowListeners:{},docListeners:{},resumeGate:null,sourceGate:null,seekGate:null,rejectSource:false,activeElement:null,scheduled:[],frames:[],clock:0},els={},all=[];
 class E {
  constructor(tag='div'){this.tagName=tag;this.children=[];this.parentElement=null;this.dataset={};this.attributes={};this.listeners={};this.value='';this.files=[];this.textContent='';this.hidden=false;this.disabled=false;this.width=1920;this.height=1080;this.readyState=4;this.duration=12;this.videoWidth=1280;this.videoHeight=720;this.paused=true;this._time=0}
  append(...es){for(const e of es){e.parentElement=this;this.children.push(e)}}
  replaceChildren(...es){for(const e of this.children)e.parentElement=null;this.children=[];this.append(...es)}
  setAttribute(k,v){this.attributes[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);else if(['hidden','disabled','open'].includes(k))this[k]=true;else this[k]=v}
  removeAttribute(k){delete this.attributes[k];if(['hidden','disabled','open'].includes(k))this[k]=false;else delete this[k]}
  querySelector(s){const m=s.match(/^\[data-([^=\]]+)(?:="([^"]*)")?\]$/);if(!m)return null;const key=m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase());for(const e of this.children){if(key in e.dataset&&(m[2]===undefined||e.dataset[key]===m[2]))return e;const found=e.querySelector(s);if(found)return found}return null}
  isEffectivelyDisabled(){if(this.disabled)return true;if(['button','input','select','textarea'].includes(this.tagName)){for(let p=this.parentElement;p;p=p.parentElement)if(p.tagName==='fieldset'&&p.disabled)return true}return false}
  focus(){for(let p=this;p;p=p.parentElement)if(p.hidden)return;if(!this.isEffectivelyDisabled()){state.activeElement=this;doc.activeElement=this}}select(){}click(){if(this.isEffectivelyDisabled())return;if(this.tagName==='a')state.downloads.push(this);return this.onclick?.()}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f)}removeEventListener(k,f){this.listeners[k]=(this.listeners[k]??[]).filter(v=>v!==f)}
  emit(k){for(const f of [...(this.listeners[k]??[])])f();this['on'+k]?.()}
  load(){queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}
  set src(v){this._src=v;const emit=()=>this.emit(state.rejectSource?'error':'loadedmetadata');if(state.sourceGate)state.sourceGate.then(emit);else queueMicrotask(emit)}get src(){return this._src}
  set currentTime(t){this._time=t;if(state.seekGate)state.seekGate.then(()=>this.emit('seeked'),()=>this.emit('error'));else queueMicrotask(()=>this.emit('seeked'))}get currentTime(){return this._time}
  getContext(){return {measureText:t=>({width:t.length*20}),drawImage(){},fillRect(){},strokeRect(){},fillText(){},save(){},restore(){}}}
  toBlob(fn){queueMicrotask(()=>fn(new Blob(['synthetic'])))}
 }
 const root=new E('document'),stack=[root],voids=new Set(['meta','input','br','hr','img','link']);
 // Only parse the static HTML shell; script contents are executed separately in vm.
 for(const match of markup.matchAll(/<\/?([a-z][a-z0-9-]*)(\s[^>]*?)?\s*>/gi)){
  const [token,rawTag,attrs='']=match,tag=rawTag.toLowerCase();if(token.startsWith('</')){while(stack.length>1&&stack.at(-1).tagName!==tag)stack.pop();if(stack.at(-1).tagName===tag)stack.pop();continue}
  const e=new E(tag);for(const a of attrs.matchAll(/([^\s=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g))e.setAttribute(a[1],a[2]??a[3]??a[4]??'');
  if(e.id){assert.equal(els[e.id],undefined,'duplicate HTML id: '+e.id);els[e.id]=e}all.push(e);stack.at(-1).append(e);if(!voids.has(tag))stack.push(e);
 }
 const nav=all.filter(e=>'step' in e.dataset),nudges=all.filter(e=>'nudge' in e.dataset);
 class AC {constructor(){this.state='running';this.destination={}}get currentTime(){return state.clock}resume(){return state.resumeGate??Promise.resolve()}decodeAudioData(){return Promise.resolve({duration:2})}close(){}createBufferSource(){const n={connect(){},start(...args){this.startArgs=args;state.scheduled.push(this)},stop(){this.stopped=true}};return n}}
 const doc={getElementById:id=>els[id],createElement:tag=>new E(tag),querySelector:s=>root.querySelector(s),querySelectorAll:s=>s==='[data-step]'?nav:s==='[data-nudge]'?nudges:[],fonts:{ready:Promise.resolve()},addEventListener:(k,f)=>state.docListeners[k]=f,hidden:false};
 const sandbox={document:doc,window:{AudioContext:AC,addEventListener:(k,f)=>state.windowListeners[k]=f},navigator:{clipboard:{writeText:async()=>{}}},confirm:()=>{state.confirmationCount++;return state.confirmations.length?state.confirmations.shift():true},URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){}},Blob,TextDecoder,Map,Set,console,queueMicrotask,setTimeout:(fn,ms)=>ms===60000?0:setTimeout(fn,ms),clearTimeout,requestAnimationFrame:f=>{state.frames.push(f);return state.frames.length},cancelAnimationFrame(){},module:{exports:{}}};
 vm.createContext(sandbox);scripts.forEach(s=>vm.runInContext(s,sandbox));
 const file=async(id,files)=>{els[id].files=files;await els[id].onchange()};
 const source=()=>file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);
 const proposal=()=>({schemaVersion:1,title:'合成',scenes:[{id:'s001',sourceIn:0,sourceOut:6,narration:'説明1',caption:'字幕1',captionPosition:'bottom',regionId:'',effect:'none'},{id:'s002',sourceIn:6,sourceOut:12,narration:'説明2',caption:'字幕2',captionPosition:'bottom',regionId:'',effect:'none'}],questions:[]});
 const apply=async()=>{els.proposal.value=JSON.stringify(proposal());await els.applyProposal.onclick()};
 const saved=()=>({...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1920,height:1080,fps:30},regions:[],credits:'合成音'});
 const wav=name=>{const a=new Uint8Array(44);a.set(Buffer.from('RIFF'));a.set(Buffer.from('WAVE'),8);return {name,arrayBuffer:async()=>a.buffer}};
 const audio=()=>file('audioFiles',[wav('s001.wav'),wav('s002.wav')]);
 const visible=e=>!e.hidden&&(!e.parentElement||visible(e.parentElement));
 const step=n=>nav[n-1].onclick();
 const active=()=>nav.filter(e=>e.attributes['aria-current']==='step').map(e=>Number(e.dataset.step));
 return {E:els,nav,state,file,source,apply,saved,wav,audio,visible,step,active,root,doc};
}
(async()=>{
 let count=0;const test=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
 await test('初期画面は録画選択中心で動画・領域・場面を隠す',()=>{const f=fixture();assert.equal(f.visible(f.E.sourceFileLabel),true);for(const id of ['sourceWorkspace','sourcePreparation','regionPanel','scenePanel','stageActions','operationBar','workflowNav','projectToolbar'])assert.equal(f.visible(f.E[id]),false,id);assert.deepEqual(f.active(),[1]);assert.ok(f.nav.slice(1).every(b=>b.disabled));assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.doesNotMatch(f.E.dirty.textContent,/保存済み/)});
 await test('録画読込後は構成だけ解禁し、場面なしのWAVを拒否',async()=>{const f=fixture();await f.source();assert.equal(f.visible(f.E.sourceWorkspace),true);assert.equal(f.visible(f.E.regionPanel),true);assert.equal(f.E.sceneTrim.hidden,true);assert.equal(f.E.workflowNav.hidden,false);assert.equal(f.E.projectToolbar.hidden,false);assert.equal(f.nav[1].disabled,false);assert.equal(f.nav[2].disabled,true);f.step(3);assert.deepEqual(f.active(),[1]);await f.file('audioFiles',[f.wav('s001.wav')]);assert.match(f.E.audioFeedback.textContent,/場面を追加してから/);assert.equal(f.E.pendingAudio.children.length,0)});
 await test('次へ・戻るの反復で入力DOM・構成・音声・保存状態を保持',async()=>{const f=fixture();await f.source();f.E.nextStep.onclick();assert.deepEqual(f.active(),[2]);await f.apply();f.E.nextStep.onclick();await f.audio();const card=f.E.sceneCards.children[0];const status=f.E.dirty.textContent;f.E.previousStep.onclick();assert.equal(f.visible(f.E.scenePanel),true);assert.equal(f.E.sceneCards.children[0],card);f.E.nextStep.onclick();assert.equal(f.visible(f.E.scenePanel),false);assert.match(f.E.audioProgress.textContent,/2 \/ 2/);assert.equal(f.E.dirty.textContent,status);assert.deepEqual(f.active(),[3]);assert.equal([1,2,3,4].filter(n=>f.visible(f.E['step'+n])).length,1)});
 await test('音声不足でも次へから不足を確認でき、再生と書出しは無効',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);assert.equal(f.E.nextStep.disabled,false);assert.match(f.E.nextStep.textContent,/不足項目/);f.E.nextStep.onclick();await tick();assert.deepEqual(f.active(),[4]);assert.equal(f.E.export.disabled,true);assert.match(f.E.exportErrors.textContent,/WAVが未対応/);f.step(3);await f.audio();assert.equal(f.E.nextStep.disabled,false);f.E.nextStep.onclick();await tick();assert.equal(f.E.export.disabled,false);assert.equal(f.E.play.disabled,false)});
 await test('JSON復元は保存時メタデータだけで動画UIを解禁しない',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);assert.deepEqual(f.active(),[1]);assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.regionPanel.hidden,true);assert.equal(f.E.sourcePreparation.hidden,true);assert.equal(f.E.sourceFileLabel.textContent,'前の録画を選ぶ');assert.equal(f.E.dirty.textContent,'JSONから再開');assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.export.disabled,true);assert.equal(f.nav[1].disabled,true);await f.source();assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.E.sceneTrim.hidden,false);assert.equal(f.nav[2].disabled,false)});
 await test('処理中は工程移動を止め、取消後に適切な操作だけ再有効化',async()=>{const f=fixture();await f.source();f.step(2);await f.apply();f.step(3);let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.audio();await tick();assert.equal(f.E.operationBar.hidden,false);assert.ok(f.nav.every(b=>b.disabled));f.step(1);assert.deepEqual(f.active(),[3]);f.E.cancel.onclick();resume();await pending;assert.equal(f.E.operationBar.hidden,true);assert.equal(f.E.editable.disabled,false);assert.equal(f.E.nextStep.disabled,false);assert.match(f.E.nextStep.textContent,/不足項目/);assert.equal(f.E.export.disabled,true);assert.equal(f.nav[1].disabled,false)});
 await test('未保存・ダウンロード開始・再編集の表示と再読込を区別',async()=>{const f=fixture();await f.source();const unsaved=f.E.dirty.textContent;f.E.saveProject.onclick();assert.equal(f.state.downloads.length,0);assert.equal(f.E.dirty.textContent,unsaved);await f.apply();f.E.saveProject.onclick();assert.equal(f.state.downloads.length,1);assert.equal(f.E.dirty.textContent,'JSONダウンロード開始済み');assert.match(f.E.status.textContent,/ブラウザーで保存結果を確認/);f.step(2);f.step(3);assert.equal(f.E.dirty.textContent,'JSONダウンロード開始済み');f.E.title.value='変更';f.E.title.onchange();assert.equal(f.E.dirty.textContent,'JSON作成後に変更あり');f.E.undo.onclick();assert.equal(f.E.dirty.textContent,'JSON作成後に変更あり');const reloaded=fixture();assert.equal(reloaded.E.dirty.textContent,'まだ保存していません');assert.equal(reloaded.E.sourceWorkspace.hidden,true)});
 await test('新規作業の取消は保持、確定で素材・構成・UIを初期化',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(3);f.E.purpose.value='入力済み';f.state.confirmations=[false];f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,2);assert.deepEqual(f.active(),[3]);f.state.confirmations=[true];f.E.newProject.onclick();assert.deepEqual(f.active(),[1]);assert.equal(f.E.sceneCards.children.length,0);assert.equal(f.E.purpose.value,'');assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.regionPanel.hidden,true);assert.equal(f.E.undo.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.export.disabled,true);await f.source();assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.nav[1].disabled,false)});
 await test('最後の場面削除で音声工程から構成に戻り取消で復帰',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(3);f.E.sceneCards.children[0].children[0].children[4].onclick();f.E.sceneCards.children[0].children[0].children[4].onclick();assert.deepEqual(f.active(),[2]);assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.equal(f.E.export.disabled,true);f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,1);assert.equal(f.E.audioFiles.disabled,false);assert.match(f.E.audioProgress.textContent,/1 \/ 1/)});
 await test('録画差替え失敗時は元の表示・工程・編集データを保持',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);const sourceInfo=f.E.sourceInfo.textContent;f.state.rejectSource=true;await f.file('sourceFile',[{name:'broken.mp4',size:200,lastModified:1}]);assert.equal(f.E.sourceInfo.textContent,sourceInfo);assert.equal(f.E.sourceWorkspace.hidden,false);assert.deepEqual(f.active(),[3]);assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.editable.disabled,false)});
 await test('ナレーション差異と長いクレジットで書出しを無効化、修正で復帰',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();assert.equal(f.E.export.disabled,false);const field=f.E.sceneCards.children[0].children[3].children[0];field.value='新しい本文';field.onchange();assert.equal(f.E.export.disabled,true);assert.match(f.E.audioProgress.textContent,/1 \/ 2/);f.E.undo.onclick();assert.equal(f.E.export.disabled,false);f.E.credits.value='あ'.repeat(200);f.E.credits.onchange();assert.equal(f.E.export.disabled,true);f.E.credits.value='合成音';f.E.credits.onchange();assert.equal(f.E.export.disabled,false)});
 await test('保存状態と独立してブラウザ離脱時の未保存警告を維持',async()=>{const f=fixture();await f.source();await f.apply();let warned=false;f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,true);f.E.saveProject.onclick();warned=false;f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,false);f.E.title.value='変更';f.E.title.onchange();f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,true)});
 await test('遅いJSON読込の取消後に旧データを適用しない',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value;let resolve;const pending=f.file('projectFile',[{text:()=>new Promise(r=>resolve=r)}]);await tick();assert.equal(f.E.newProject.disabled,true);assert.equal(f.E.operationBar.hidden,false);f.E.newProject.onclick();assert.equal(f.E.title.value,title);f.E.cancel.onclick();resolve(JSON.stringify({...f.saved(),title:'古い読込'}));await pending;assert.equal(f.E.title.value,title);assert.equal(f.E.operationBar.hidden,true);assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.E.editable.disabled,false)});
 await test('最後の未対応WAVを外すと対応待ち見出しも消える',async()=>{const f=fixture();await f.source();await f.apply();await f.file('audioFiles',[f.wav('unknown.wav')]);assert.equal(f.E.pendingAudioSection.hidden,false);f.E.pendingAudio.children[0].children[3].onclick();assert.equal(f.E.pendingAudio.children.length,0);assert.equal(f.E.pendingAudioSection.hidden,true)});
 await test('別JSONの復元に前の依頼用入力を持ち越さない',async()=>{const f=fixture();await f.source();await f.apply();for(const id of ['purpose','audience','extraTimes','regionName','proposal'])f.E[id].value='前の作業';f.E.target.value='180';await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);for(const id of ['purpose','audience','extraTimes','regionName','proposal'])assert.equal(f.E[id].value,'');assert.equal(f.E.target.value,'60')});
 await test('履歴キャッシュ退避後も録画読込の後始末まで新規作成を拒否',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value;let resolve;f.state.sourceGate=new Promise(r=>resolve=r);const pending=f.file('sourceFile',[{name:'replacement.mp4',size:200,lastModified:1}]);await tick();f.state.windowListeners.pagehide({persisted:true});assert.equal(f.E.newProject.disabled,true);assert.equal(f.E.editable.disabled,true);f.E.newProject.onclick();assert.equal(f.E.title.value,title);resolve();await pending;assert.equal(f.E.editable.disabled,false);assert.match(f.E.sourceInfo.textContent,/synthetic.mp4/);f.E.newProject.onclick();assert.equal(f.E.sourceWorkspace.hidden,true);await tick();assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.sceneCards.children.length,0)});
 await test('履歴キャッシュ退避後もWAV準備の終了までは新規作成を拒否',async()=>{const f=fixture();await f.source();await f.apply();let resolve;f.state.resumeGate=new Promise(r=>resolve=r);const pending=f.audio();await tick();f.state.windowListeners.pagehide({persisted:true});assert.equal(f.E.newProject.disabled,true);f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,2);resolve();await pending;assert.equal(f.E.newProject.disabled,false);assert.equal(f.E.editable.disabled,false);assert.match(f.E.audioProgress.textContent,/0 \/ 2/);f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,0)});
 await test('空の新規作成は確認不要で取消履歴も復活しない',()=>{const f=fixture();f.E.newProject.onclick();assert.equal(f.state.confirmationCount,0);assert.equal(f.E.undo.disabled,true);f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,0);assert.equal(f.E.sourceWorkspace.hidden,true)});
 await test('画像生成中は移動・新規作成を拒否し取消後も元の構成を保持',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value,pending=f.E.storyboard.onclick();assert.equal(f.E.editable.disabled,true);f.step(2);assert.deepEqual(f.active(),[1]);f.E.newProject.onclick();assert.equal(f.E.title.value,title);f.E.cancel.onclick();await pending;assert.equal(f.E.downloads.children.length,0);assert.equal(f.E.title.value,title);assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.editable.disabled,false);f.E.newProject.onclick();f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,0)});
 await test('ファイル選択ラベル・工程所属・初期hidden属性が静的HTMLに存在',()=>{const f=fixture();for(const id of ['sourceFile','projectFile','audioFiles'])assert.match(markup,new RegExp('for="'+id+'"'));assert.equal(f.E.scenePanel.parentElement.id,'step2');assert.equal(f.E.script.parentElement.parentElement.parentElement.id,'step3');for(const id of ['sourceWorkspace','sourcePreparation','regionPanel','step2','step3','step4'])assert.match(markup,new RegExp('id="'+id+'"[^>]* hidden'));assert.match(markup,/自動保存はありません/);assert.doesNotMatch(markup,/保存済み/)});

 await test('各場面から元動画の開始位置を開いて同じ場面へ戻る',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(2);f.E.saveProject.onclick();const dirty=f.E.dirty.textContent,card=f.E.sceneCards.children[1],sourceButton=card.querySelector('[data-action="view-source"]');await sourceButton.click();assert.deepEqual(f.active(),[1]);assert.equal(f.E.sourceTrimDetails.open,true);assert.equal(f.E.selectedScene.value,'s002');assert.equal(f.E.sourceVideo.currentTime,6);assert.equal(f.E.sourceTime.value,'6.0');assert.equal(f.E.sourceReturnBar.hidden,false);assert.match(f.E.sourceSceneContext.textContent,/s002/);assert.equal(f.state.activeElement,f.E.sourceHeading);f.E.returnToComposition.click();assert.deepEqual(f.active(),[2]);assert.equal(f.state.activeElement,sourceButton);assert.equal(f.E.sceneCards.children[1],card);assert.equal(f.E.dirty.textContent,dirty);assert.match(f.E.audioProgress.textContent,/2 \/ 2/)});
 await test('場面映像の準備中は連打・戻る・新規作成を防ぎ取消後に古い結果を出さない',async()=>{const f=fixture();await f.source();await f.apply();f.step(2);let resolve;f.state.seekGate=new Promise(r=>resolve=r);const sourceButton=f.E.sceneCards.children[1].querySelector('[data-action="view-source"]'),pending=sourceButton.click();assert.equal(f.E.editable.disabled,true);f.E.returnToComposition.click();f.E.newProject.onclick();await sourceButton.onclick();assert.equal(f.E.sceneCards.children.length,2);assert.deepEqual(f.active(),[1]);f.E.cancel.click();assert.equal(f.E.cancel.disabled,true);const focused=f.state.activeElement;resolve();await pending;assert.equal(f.E.editable.disabled,false);assert.equal(f.state.activeElement,focused);assert.doesNotMatch(f.E.sourceFeedback.textContent,/表示しています/);f.E.newProject.click();assert.equal(f.E.sourceReturnBar.hidden,true);assert.equal(f.E.sourceTrimDetails.open,false);assert.equal(f.state.activeElement,f.E.sourceHeading)});
 await test('取り消した場面シークの遅い失敗は中止表示を上書きしない',async()=>{const f=fixture();await f.source();await f.apply();let reject;f.state.seekGate=new Promise((_,r)=>reject=r);const pending=f.E.sceneCards.children[1].querySelector('[data-action="view-source"]').click();f.E.cancel.click();const status=f.E.status.textContent;reject(Error('late seek'));await pending;assert.match(f.E.status.textContent,/処理を中止しました/);assert.doesNotMatch(f.E.status.textContent,/後始末/);assert.equal(f.E.sourceFeedback.textContent,'');assert.equal(f.E.editable.disabled,false)});
 await test('工程移動は見出しにフォーカスし拒否された移動はフォーカスを動かさない',async()=>{const f=fixture();f.E.sourceHeading.focus();f.step(3);assert.equal(f.state.activeElement,f.E.sourceHeading);await f.source();f.step(2);assert.equal(f.state.activeElement,f.E.structureHeading);assert.equal(f.E.structureHeading.attributes.tabindex,'-1');await f.apply();f.step(3);assert.equal(f.state.activeElement,f.E.audioHeading);f.step(4);await tick();assert.equal(f.state.activeElement,f.E.exportHeading);f.E.previousStep.click();assert.equal(f.state.activeElement,f.E.audioHeading)});
 await test('プレビュー近くの停止は編集fieldsetの無効化中も操作できる',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();const pending=f.E.play.click();await tick();await tick();assert.equal(f.E.editable.disabled,true);assert.equal(f.E.exportSettings.disabled,true);assert.equal(f.E.play.isEffectivelyDisabled(),true);assert.equal(f.E.previewStop.isEffectivelyDisabled(),false);assert.equal(f.E.cancel.hidden,true);assert.equal(f.E.operationBar.hidden,true);for(let p=f.E.previewStop.parentElement;p;p=p.parentElement)assert.notEqual(p.tagName,'fieldset');f.E.previewStop.click();f.E.previewStop.click();await pending;assert.equal(f.E.editable.disabled,false);assert.equal(f.E.previewStop.disabled,true);assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)});
 await test('プレビューの音声準備待ちを近くの停止で中止し後から音を出さない',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.E.play.click();await tick();f.E.previewStop.click();assert.equal(f.E.previewStop.disabled,true);resume();await pending;assert.equal(f.state.scheduled.length,0);assert.equal(f.E.editable.disabled,false);assert.equal(f.E.exportResult.children.length,0)});
 await test('再生と停止の反復で音声が重ならず同じ停止操作を使う',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();for(let i=0;i<3;i++){const pending=f.E.play.click();await tick();await tick();assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,2);assert.equal(f.E.previewStop.textContent,'再生を停止');f.E.previewStop.click();await pending;assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)}});
 await test('現在位置からの再生と先頭からの再生を区別する',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();f.E.timeline.value='7';await f.E.timeline.onchange();const pending=f.E.play.click();await tick();await tick();assert.equal(f.E.sourceVideo.currentTime,7);assert.equal(f.state.scheduled.length,1);assert.ok(Math.abs(f.state.scheduled[0].startArgs[1]-.85)<.00001);f.E.previewStop.click();await pending;const restart=f.E.playFromStart.click();await tick();await tick();assert.equal(f.E.sourceVideo.currentTime,0);assert.equal(Number(f.E.timeline.value),0);f.E.previewStop.click();await restart});
 await test('終端からの再生は先頭へ戻して再生できる',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();f.E.timeline.value='12';await f.E.timeline.onchange();assert.match(f.E.play.textContent,/先頭からもう一度/);const pending=f.E.play.click();await tick();await tick();assert.equal(Number(f.E.timeline.value),0);assert.equal(f.E.sourceVideo.currentTime,0);f.E.previewStop.click();await pending});
 await test('JSONエラーは工程移動やコピーで消えず成功時だけ更新する',async()=>{const f=fixture();await f.source();await f.apply();f.step(2);f.E.proposal.value='{';await f.E.applyProposal.click();const message=f.E.proposalFeedback.textContent;assert.match(message,/JSON/);assert.equal(f.E.proposal.attributes['aria-invalid'],'true');f.step(3);await f.E.copyScript.click();f.step(2);await f.E.copyPrompt.click();f.E.title.value='別タイトル';f.E.title.onchange();assert.equal(f.E.proposalFeedback.textContent,message);await f.apply();assert.match(f.E.proposalFeedback.textContent,/構成を適用/);assert.equal(f.E.proposal.attributes['aria-invalid'],undefined)});
 await test('音声の読込エラーは別ファイル成功後も残り同名の再読込で解消する',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);await f.file('audioFiles',[{name:'broken.wav',arrayBuffer:async()=>new Uint8Array(3).buffer}]);assert.match(f.E.audioFeedback.textContent,/broken.wav/);await f.file('audioFiles',[f.wav('s001.wav')]);assert.match(f.E.audioFeedback.textContent,/broken.wav/);f.step(2);f.step(3);assert.match(f.E.audioFeedback.textContent,/RIFF WAV/);await f.file('audioFiles',[f.wav('broken.wav')]);assert.doesNotMatch(f.E.audioFeedback.textContent,/RIFF WAV/);assert.equal(f.E.dismissAudioErrors.hidden,true)});
 await test('音声エラーを閉じても対応状態と書出しガードは変えない',async()=>{const f=fixture();await f.source();await f.apply();await f.file('audioFiles',[{name:'bad.wav',arrayBuffer:async()=>new Uint8Array(1).buffer}]);assert.equal(f.E.dismissAudioErrors.hidden,false);f.E.dismissAudioErrors.onclick();assert.equal(f.E.audioFeedback.textContent,'');assert.equal(f.E.dismissAudioErrors.hidden,true);assert.equal(f.E.export.disabled,true);assert.match(f.E.exportErrors.textContent,/WAVが未対応/)});
 await test('場面入力のエラーは該当カードに残り別場面の編集では消えない',async()=>{const f=fixture();await f.source();await f.apply();const out=f.E.sceneCards.children[0].children[1].children[1].children[0];out.value=99;out.onchange();let notice=f.E.sceneCards.children[0].querySelector('[data-scene-feedback]');assert.match(notice.textContent,/動画長を超え/);const other=f.E.sceneCards.children[1].children[2].children[0];other.value='別場面';other.onchange();assert.match(notice.textContent,/動画長を超え/);f.step(3);f.step(2);assert.match(notice.textContent,/前の値を保持/);const valid=f.E.sceneCards.children[0].children[1].children[1].children[0];valid.value=5;valid.onchange();assert.equal(f.E.sceneCards.children[0].querySelector('[data-scene-feedback]').textContent,'');assert.equal(valid.attributes['aria-describedby'],'scene-feedback-s001')});
 await test('使用中領域の警告は関連付けを解消するまで保持する',async()=>{const f=fixture();const p=f.saved();p.regions=[{id:'r01',name:'対象',x:.1,y:.1,w:.2,h:.2}];p.scenes[0].regionId='r01';p.scenes[0].effect='highlight';await f.file('projectFile',[{text:async()=>JSON.stringify(p)}]);await f.source();f.E.regions.children[0].children[1].onclick();assert.match(f.E.regionFeedback.textContent,/使用中/);f.step(2);await f.E.copyPrompt.click();assert.match(f.E.regionFeedback.textContent,/使用中/);const region=f.E.sceneCards.children[0].children[4].children[2].children[0];region.value='';region.onchange();assert.equal(f.E.regionFeedback.textContent,'');f.step(1);f.E.regions.children[0].children[1].onclick();assert.equal(f.E.regions.children.length,0)});
 await test('新規作成とJSON復元は前の作業の局所エラーを残さない',async()=>{const f=fixture();await f.source();await f.apply();f.E.proposal.value='{';await f.E.applyProposal.click();f.E.addRegion.onclick();await f.file('audioFiles',[{name:'bad.wav',arrayBuffer:async()=>new Uint8Array(1).buffer}]);f.E.newProject.onclick();for(const id of ['proposalFeedback','regionFeedback','audioFeedback'])assert.equal(f.E[id].textContent,'');await f.source();await f.apply();f.E.proposal.value='{';await f.E.applyProposal.click();await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);assert.equal(f.E.proposalFeedback.textContent,'');assert.equal(f.state.activeElement,f.E.sourceHeading)});
 await test('代表画像の生成と各PNGのダウンロード開始を分けて数える',async()=>{const f=fixture();await f.source();f.E.extraTimes.value='1,2,4,5,7,8';await f.E.storyboard.click();assert.equal(f.E.downloads.children.length,2);assert.match(f.E.storyboardStatus.textContent,/ダウンロード開始 0 \/ 2/);assert.doesNotMatch(f.E.storyboardStatus.textContent,/保存済み/);const link=f.E.downloads.children[0];link.click();link.click();assert.match(f.E.storyboardStatus.textContent,/ダウンロード開始 1 \/ 2/);await f.E.singleFrame.click();assert.match(f.E.storyboardStatus.textContent,/ダウンロード開始 1 \/ 2/);f.step(2);assert.match(f.E.copilotPreparation.textContent,/2 ファイル中 1 ファイル/)});
 await test('画像再生成の取消では既存画像と開始数を保持し成功時は数え直す',async()=>{const f=fixture();await f.source();await f.E.storyboard.click();const link=f.E.downloads.children[0];link.click();const pending=f.E.storyboard.click();f.E.cancel.click();await pending;assert.equal(f.E.downloads.children[0],link);assert.match(f.E.storyboardStatus.textContent,/ダウンロード開始 1 \/ 1/);await f.E.storyboard.click();assert.notEqual(f.E.downloads.children[0],link);assert.match(f.E.storyboardStatus.textContent,/ダウンロード開始 0 \/ 1/)});
 await test('目的の空欄を案内し構成から入力位置へ戻れる',async()=>{const f=fixture();await f.source();f.E.purpose.value='  ';f.E.purpose.onchange();assert.notEqual(f.E.purposeHint.textContent,'');f.step(2);assert.match(f.E.copilotPreparation.textContent,/目的が未入力/);f.E.reviewPreparation.click();assert.deepEqual(f.active(),[1]);assert.equal(f.state.activeElement,f.E.purpose);f.E.purpose.value='申請手順';f.E.purpose.onchange();assert.equal(f.E.purposeHint.textContent,'');f.step(2);assert.doesNotMatch(f.E.copilotPreparation.textContent,/目的が未入力/)});
 await test('場面操作の名前と並べ替え境界が支援技術にも伝わる',async()=>{const f=fixture();await f.source();await f.apply();const first=f.E.sceneCards.children[0].children[0],last=f.E.sceneCards.children[1].children[0];assert.equal(first.children[2].attributes['aria-label'],'s001を前へ移動');assert.equal(first.children[3].attributes['aria-label'],'s001を後ろへ移動');assert.equal(first.children[4].attributes['aria-label'],'s001を削除');assert.equal(first.children[5].attributes['aria-label'],'s001の元動画を見る');assert.equal(first.children[2].disabled,true);assert.equal(first.children[3].disabled,false);assert.equal(last.children[3].disabled,true)});
 await test('プレビューの位置準備完了と非表示中断を実際の状態で案内する',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();assert.match(f.E.previewStatus.textContent,/0.0秒の映像/);const pending=f.E.play.click();await tick();await tick();f.doc.hidden=true;f.state.docListeners.visibilitychange();await pending;assert.match(f.E.previewStatus.textContent,/非表示になったため中断/);assert.doesNotMatch(f.E.previewStatus.textContent,/再生が終了/);assert.equal(f.state.scheduled.filter(n=>!n.stopped).length,0)});
 await test('元動画の開始終了ボタンのエラーをその場で表示する',async()=>{const f=fixture();await f.source();await f.apply();await f.E.sceneCards.children[1].querySelector('[data-action="view-source"]').click();f.E.setOut.click();assert.match(f.E.sourceFeedback.textContent,/開始 < 終了/);assert.match(f.E.sourceFeedback.textContent,/前の値を保持/);assert.equal(f.E.sceneCards.children[1].children[1].children[1].children[0].value,12);f.E.sourceVideo.currentTime=10;await tick();f.E.setOut.click();assert.match(f.E.sourceFeedback.textContent,/区間を変更/);assert.equal(f.E.sceneCards.children[1].querySelector('[data-scene-feedback]').textContent,'')});
 await test('手動WAV対応の注意は未解決の読込エラーを隠さない',async()=>{const f=fixture();await f.source();await f.apply();await f.file('audioFiles',[{name:'bad.wav',arrayBuffer:async()=>new Uint8Array(1).buffer},f.wav('unknown.wav')]);const row=f.E.pendingAudio.children[0];row.children[2].onclick();assert.match(f.E.audioFeedback.textContent,/bad.wav/);assert.match(f.E.audioFeedback.textContent,/対応する場面を選んで/);row.children[1].value='s001';row.children[2].onclick();assert.match(f.E.audioFeedback.textContent,/bad.wav/);assert.match(f.E.audioFeedback.textContent,/対応付けました/);assert.doesNotMatch(f.E.audioFeedback.textContent,/unknown.wav：手動対応付けが必要/)});
 await test('領域の変更は同じ場面の無関係な区間エラーを消さない',async()=>{const f=fixture();await f.source();await f.apply();const out=f.E.sceneCards.children[0].children[1].children[1].children[0];out.value=99;out.onchange();const region=f.E.sceneCards.children[0].children[4].children[2].children[0];region.value='';region.onchange();assert.match(f.E.sceneCards.children[0].querySelector('[data-scene-feedback]').textContent,/動画長を超え/)});
 await test('取り消したプレビュー位置準備は終了後に待機表示を残さない',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(4);await tick();await f.E.export.onclick();const existingError=f.E.exportFeedback.textContent;let resolve;f.state.seekGate=new Promise(r=>resolve=r);f.E.timeline.value='7';const pending=f.E.timeline.onchange();f.E.previewStop.click();resolve();await pending;assert.equal(f.E.previewStop.disabled,true);assert.match(f.E.previewStatus.textContent,/中止しました/);assert.doesNotMatch(f.E.previewStatus.textContent,/準備しています|後始末/);assert.equal(f.E.exportFeedback.textContent,existingError)});
 await test('別の未使用領域を削除しても使用中領域の警告は消えない',async()=>{const f=fixture();const p=f.saved();p.regions=[{id:'r01',name:'使用中',x:.1,y:.1,w:.2,h:.2},{id:'r02',name:'未使用',x:.4,y:.4,w:.2,h:.2}];p.scenes[0].regionId='r01';p.scenes[0].effect='highlight';await f.file('projectFile',[{text:async()=>JSON.stringify(p)}]);await f.source();f.E.regions.children[0].children[1].onclick();f.E.regions.children[1].children[1].onclick();assert.equal(f.E.regions.children.length,1);assert.match(f.E.regionFeedback.textContent,/r01.*使用中/)});
 console.log(count+' workflow model tests passed. Visual layout, real dialogs, and browser export remain unverified.');
})().catch(e=>{console.error(e.message+'\n'+e.stack.split('\n').slice(1,4).join('\n'));process.exitCode=1});
