// Non-browser workflow model: HTML ancestry plus deterministic DOM/media stubs.
// Does not render pixels, open a local app, or qualify real codecs and file dialogs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const markup=html.slice(0,html.indexOf('<script>')),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
 const state={confirmations:[],confirmationCount:0,downloads:[],windowListeners:{},docListeners:{},resumeGate:null,sourceGate:null,rejectSource:false},els={},all=[];
 class E {
  constructor(tag='div'){this.tagName=tag;this.children=[];this.parentElement=null;this.dataset={};this.attributes={};this.listeners={};this.value='';this.files=[];this.textContent='';this.hidden=false;this.disabled=false;this.width=1920;this.height=1080;this.readyState=4;this.duration=12;this.videoWidth=1280;this.videoHeight=720;this.paused=true;this._time=0}
  append(...es){for(const e of es){e.parentElement=this;this.children.push(e)}}
  replaceChildren(...es){for(const e of this.children)e.parentElement=null;this.children=[];this.append(...es)}
  setAttribute(k,v){this.attributes[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);else if(['hidden','disabled','open'].includes(k))this[k]=true;else this[k]=v}
  removeAttribute(k){delete this.attributes[k];if(['hidden','disabled','open'].includes(k))this[k]=false;else delete this[k]}
  querySelector(s){const m=s.match(/^\[data-([^=\]]+)(?:="([^"]*)")?\]$/);if(!m)return null;const key=m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase());for(const e of this.children){if(key in e.dataset&&(m[2]===undefined||e.dataset[key]===m[2]))return e;const found=e.querySelector(s);if(found)return found}return null}
  focus(){}select(){}click(){if(this.tagName==='a')state.downloads.push(this);if(!this.disabled)this.onclick?.()}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f)}removeEventListener(k,f){this.listeners[k]=(this.listeners[k]??[]).filter(v=>v!==f)}
  emit(k){for(const f of [...(this.listeners[k]??[])])f();this['on'+k]?.()}
  load(){queueMicrotask(()=>{this.emit('loadedmetadata');this.emit('loadeddata')})}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}
  set src(v){this._src=v;const emit=()=>this.emit(state.rejectSource?'error':'loadedmetadata');if(state.sourceGate)state.sourceGate.then(emit);else queueMicrotask(emit)}get src(){return this._src}
  set currentTime(t){this._time=t;queueMicrotask(()=>this.emit('seeked'))}get currentTime(){return this._time}
  getContext(){return {measureText:t=>({width:t.length*20}),drawImage(){},fillRect(){},strokeRect(){},fillText(){},save(){},restore(){}}}
  toBlob(fn){queueMicrotask(()=>fn(new Blob(['synthetic'])))}
 }
 const root=new E('document'),stack=[root],voids=new Set(['meta','input','br','hr','img','link']);
 // Only parse the static HTML shell; script contents are executed separately in vm.
 for(const match of markup.matchAll(/<\/?([a-z][a-z0-9-]*)(\s[^>]*?)?\s*>/gi)){
  const [token,rawTag,attrs='']=match,tag=rawTag.toLowerCase();if(token.startsWith('</')){while(stack.length>1&&stack.at(-1).tagName!==tag)stack.pop();if(stack.at(-1).tagName===tag)stack.pop();continue}
  const e=new E(tag);for(const a of attrs.matchAll(/([^\s=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g))e.setAttribute(a[1],a[2]??a[3]??a[4]??'');
  if(e.id){assert.equal(els[e.id],undefined,'duplicate HTML id: '+e.id);els[e.id]=e}all.push(e);stack.at(-1).append(e);if(!voids.has(tag))stack.push(e);
 }
 const nav=all.filter(e=>'step' in e.dataset),nudges=all.filter(e=>'nudge' in e.dataset);
 class AC {constructor(){this.state='running';this.destination={};this.currentTime=0}resume(){return state.resumeGate??Promise.resolve()}decodeAudioData(){return Promise.resolve({duration:2})}close(){}createBufferSource(){return {connect(){},start(){},stop(){}}}}
 const doc={getElementById:id=>els[id],createElement:tag=>new E(tag),querySelector:s=>root.querySelector(s),querySelectorAll:s=>s==='[data-step]'?nav:s==='[data-nudge]'?nudges:[],fonts:{ready:Promise.resolve()},addEventListener:(k,f)=>state.docListeners[k]=f,hidden:false};
 const sandbox={document:doc,window:{AudioContext:AC,addEventListener:(k,f)=>state.windowListeners[k]=f},navigator:{clipboard:{writeText:async()=>{}}},confirm:()=>{state.confirmationCount++;return state.confirmations.length?state.confirmations.shift():true},URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){}},Blob,TextDecoder,Map,Set,console,queueMicrotask,setTimeout:(fn,ms)=>ms===60000?0:setTimeout(fn,ms),clearTimeout,requestAnimationFrame:()=>0,cancelAnimationFrame(){},module:{exports:{}}};
 vm.createContext(sandbox);scripts.forEach(s=>vm.runInContext(s,sandbox));
 const file=async(id,files)=>{els[id].files=files;await els[id].onchange()};
 const source=()=>file('sourceFile',[{name:'synthetic.mp4',size:100,lastModified:0}]);
 const proposal=()=>({schemaVersion:1,title:'合成',scenes:[{id:'s001',sourceIn:0,sourceOut:6,narration:'説明1',caption:'字幕1',captionPosition:'bottom',regionId:'',effect:'none'},{id:'s002',sourceIn:6,sourceOut:12,narration:'説明2',caption:'字幕2',captionPosition:'bottom',regionId:'',effect:'none'}],questions:[]});
 const apply=async()=>{els.proposal.value=JSON.stringify(proposal());await els.applyProposal.onclick()};
 const saved=()=>({...proposal(),source:{name:'synthetic.mp4',size:100,lastModified:0,duration:12,width:1280,height:720},output:{width:1920,height:1080,fps:30},regions:[],credits:'合成音'});
 const wav=name=>{const a=new Uint8Array(44);a.set(Buffer.from('RIFF'));a.set(Buffer.from('WAVE'),8);return {name,arrayBuffer:async()=>a.buffer}};
 const audio=()=>file('audioFiles',[wav('s001.wav'),wav('s002.wav')]);
 const visible=e=>!e.hidden&&(!e.parentElement||visible(e.parentElement));
 const step=n=>nav[n-1].onclick();
 const active=()=>nav.filter(e=>e.attributes['aria-current']==='step').map(e=>Number(e.dataset.step));
 return {E:els,nav,state,file,source,apply,saved,wav,audio,visible,step,active,root,doc};
}
(async()=>{
 let count=0;const test=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
 await test('初期画面は録画選択中心で動画・領域・場面を隠す',()=>{const f=fixture();assert.equal(f.visible(f.E.sourceFileLabel),true);for(const id of ['sourceWorkspace','sourcePreparation','regionPanel','scenePanel','stageActions','operationBar','workflowNav','projectToolbar'])assert.equal(f.visible(f.E[id]),false,id);assert.deepEqual(f.active(),[1]);assert.ok(f.nav.slice(1).every(b=>b.disabled));assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.doesNotMatch(f.E.dirty.textContent,/保存済み/)});
 await test('録画読込後は構成だけ解禁し、場面なしのWAVを拒否',async()=>{const f=fixture();await f.source();assert.equal(f.visible(f.E.sourceWorkspace),true);assert.equal(f.visible(f.E.regionPanel),true);assert.equal(f.E.sceneTrim.hidden,true);assert.equal(f.E.workflowNav.hidden,false);assert.equal(f.E.projectToolbar.hidden,false);assert.equal(f.nav[1].disabled,false);assert.equal(f.nav[2].disabled,true);f.step(3);assert.deepEqual(f.active(),[1]);await f.file('audioFiles',[f.wav('s001.wav')]);assert.match(f.E.status.textContent,/場面を追加してから/);assert.equal(f.E.pendingAudio.children.length,0)});
 await test('次へ・戻るの反復で入力DOM・構成・音声・保存状態を保持',async()=>{const f=fixture();await f.source();f.E.nextStep.onclick();assert.deepEqual(f.active(),[2]);await f.apply();f.E.nextStep.onclick();await f.audio();const card=f.E.sceneCards.children[0];const status=f.E.dirty.textContent;f.E.previousStep.onclick();assert.equal(f.visible(f.E.scenePanel),true);assert.equal(f.E.sceneCards.children[0],card);f.E.nextStep.onclick();assert.equal(f.visible(f.E.scenePanel),false);assert.match(f.E.audioProgress.textContent,/2 \/ 2/);assert.equal(f.E.dirty.textContent,status);assert.deepEqual(f.active(),[3]);assert.equal([1,2,3,4].filter(n=>f.visible(f.E['step'+n])).length,1)});
 await test('音声が揃うまで次へは無効、書出しタブでは不足理由を確認可能',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);assert.equal(f.E.nextStep.disabled,true);f.E.nextStep.onclick();assert.deepEqual(f.active(),[3]);f.step(4);await tick();assert.deepEqual(f.active(),[4]);assert.equal(f.E.export.disabled,true);assert.match(f.E.exportErrors.textContent,/WAVが未対応/);f.step(3);await f.audio();assert.equal(f.E.nextStep.disabled,false);f.E.nextStep.onclick();await tick();assert.equal(f.E.export.disabled,false);assert.equal(f.E.play.disabled,false)});
 await test('JSON復元は保存時メタデータだけで動画UIを解禁しない',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);assert.deepEqual(f.active(),[1]);assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.regionPanel.hidden,true);assert.equal(f.E.sourcePreparation.hidden,true);assert.equal(f.E.sourceFileLabel.textContent,'前の録画を選ぶ');assert.equal(f.E.dirty.textContent,'JSONから再開');assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.export.disabled,true);assert.equal(f.nav[1].disabled,true);await f.source();assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.E.sceneTrim.hidden,false);assert.equal(f.nav[2].disabled,false)});
 await test('処理中は工程移動を止め、取消後に適切な操作だけ再有効化',async()=>{const f=fixture();await f.source();f.step(2);await f.apply();f.step(3);let resume;f.state.resumeGate=new Promise(r=>resume=r);const pending=f.audio();await tick();assert.equal(f.E.operationBar.hidden,false);assert.ok(f.nav.every(b=>b.disabled));f.step(1);assert.deepEqual(f.active(),[3]);f.E.cancel.onclick();resume();await pending;assert.equal(f.E.operationBar.hidden,true);assert.equal(f.E.editable.disabled,false);assert.equal(f.E.nextStep.disabled,true);assert.equal(f.E.export.disabled,true);assert.equal(f.nav[1].disabled,false)});
 await test('未保存・ダウンロード開始・再編集の表示と再読込を区別',async()=>{const f=fixture();await f.source();const unsaved=f.E.dirty.textContent;f.E.saveProject.onclick();assert.equal(f.state.downloads.length,0);assert.equal(f.E.dirty.textContent,unsaved);await f.apply();f.E.saveProject.onclick();assert.equal(f.state.downloads.length,1);assert.equal(f.E.dirty.textContent,'JSONダウンロード開始済み');assert.match(f.E.status.textContent,/ブラウザーで保存結果を確認/);f.step(2);f.step(3);assert.equal(f.E.dirty.textContent,'JSONダウンロード開始済み');f.E.title.value='変更';f.E.title.onchange();assert.equal(f.E.dirty.textContent,'JSON作成後に変更あり');f.E.undo.onclick();assert.equal(f.E.dirty.textContent,'JSON作成後に変更あり');const reloaded=fixture();assert.equal(reloaded.E.dirty.textContent,'まだ保存していません');assert.equal(reloaded.E.sourceWorkspace.hidden,true)});
 await test('新規作業の取消は保持、確定で素材・構成・UIを初期化',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(3);f.E.purpose.value='入力済み';f.state.confirmations=[false];f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,2);assert.deepEqual(f.active(),[3]);f.state.confirmations=[true];f.E.newProject.onclick();assert.deepEqual(f.active(),[1]);assert.equal(f.E.sceneCards.children.length,0);assert.equal(f.E.purpose.value,'');assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.regionPanel.hidden,true);assert.equal(f.E.undo.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.export.disabled,true);await f.source();assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.nav[1].disabled,false)});
 await test('最後の場面削除で音声工程から構成に戻り取消で復帰',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();f.step(3);f.E.sceneCards.children[0].children[0].children[4].onclick();f.E.sceneCards.children[0].children[0].children[4].onclick();assert.deepEqual(f.active(),[2]);assert.equal(f.E.audioFiles.disabled,true);assert.equal(f.E.saveProject.disabled,true);assert.equal(f.E.export.disabled,true);f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,1);assert.equal(f.E.audioFiles.disabled,false);assert.match(f.E.audioProgress.textContent,/1 \/ 1/)});
 await test('録画差替え失敗時は元の表示・工程・編集データを保持',async()=>{const f=fixture();await f.source();await f.apply();f.step(3);const sourceInfo=f.E.sourceInfo.textContent;f.state.rejectSource=true;await f.file('sourceFile',[{name:'broken.mp4',size:200,lastModified:1}]);assert.equal(f.E.sourceInfo.textContent,sourceInfo);assert.equal(f.E.sourceWorkspace.hidden,false);assert.deepEqual(f.active(),[3]);assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.editable.disabled,false)});
 await test('ナレーション差異と長いクレジットで書出しを無効化、修正で復帰',async()=>{const f=fixture();await f.source();await f.apply();await f.audio();assert.equal(f.E.export.disabled,false);const field=f.E.sceneCards.children[0].children[3].children[0];field.value='新しい本文';field.onchange();assert.equal(f.E.export.disabled,true);assert.match(f.E.audioProgress.textContent,/1 \/ 2/);f.E.undo.onclick();assert.equal(f.E.export.disabled,false);f.E.credits.value='あ'.repeat(200);f.E.credits.onchange();assert.equal(f.E.export.disabled,true);f.E.credits.value='合成音';f.E.credits.onchange();assert.equal(f.E.export.disabled,false)});
 await test('保存状態と独立してブラウザ離脱時の未保存警告を維持',async()=>{const f=fixture();await f.source();await f.apply();let warned=false;f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,true);f.E.saveProject.onclick();warned=false;f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,false);f.E.title.value='変更';f.E.title.onchange();f.state.windowListeners.beforeunload({preventDefault(){warned=true}});assert.equal(warned,true)});
 await test('遅いJSON読込の取消後に旧データを適用しない',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value;let resolve;const pending=f.file('projectFile',[{text:()=>new Promise(r=>resolve=r)}]);await tick();assert.equal(f.E.newProject.disabled,true);assert.equal(f.E.operationBar.hidden,false);f.E.newProject.onclick();assert.equal(f.E.title.value,title);f.E.cancel.onclick();resolve(JSON.stringify({...f.saved(),title:'古い読込'}));await pending;assert.equal(f.E.title.value,title);assert.equal(f.E.operationBar.hidden,true);assert.equal(f.E.sourceWorkspace.hidden,false);assert.equal(f.E.editable.disabled,false)});
 await test('最後の未対応WAVを外すと対応待ち見出しも消える',async()=>{const f=fixture();await f.source();await f.apply();await f.file('audioFiles',[f.wav('unknown.wav')]);assert.equal(f.E.pendingAudioSection.hidden,false);f.E.pendingAudio.children[0].children[3].onclick();assert.equal(f.E.pendingAudio.children.length,0);assert.equal(f.E.pendingAudioSection.hidden,true)});
 await test('別JSONの復元に前の依頼用入力を持ち越さない',async()=>{const f=fixture();await f.source();await f.apply();for(const id of ['purpose','audience','extraTimes','regionName','proposal'])f.E[id].value='前の作業';f.E.target.value='180';await f.file('projectFile',[{text:async()=>JSON.stringify(f.saved())}]);for(const id of ['purpose','audience','extraTimes','regionName','proposal'])assert.equal(f.E[id].value,'');assert.equal(f.E.target.value,'60')});
 await test('履歴キャッシュ退避後も録画読込の後始末まで新規作成を拒否',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value;let resolve;f.state.sourceGate=new Promise(r=>resolve=r);const pending=f.file('sourceFile',[{name:'replacement.mp4',size:200,lastModified:1}]);await tick();f.state.windowListeners.pagehide({persisted:true});assert.equal(f.E.newProject.disabled,true);assert.equal(f.E.editable.disabled,true);f.E.newProject.onclick();assert.equal(f.E.title.value,title);resolve();await pending;assert.equal(f.E.editable.disabled,false);assert.match(f.E.sourceInfo.textContent,/synthetic.mp4/);f.E.newProject.onclick();assert.equal(f.E.sourceWorkspace.hidden,true);await tick();assert.equal(f.E.sourceWorkspace.hidden,true);assert.equal(f.E.sceneCards.children.length,0)});
 await test('履歴キャッシュ退避後もWAV準備の終了までは新規作成を拒否',async()=>{const f=fixture();await f.source();await f.apply();let resolve;f.state.resumeGate=new Promise(r=>resolve=r);const pending=f.audio();await tick();f.state.windowListeners.pagehide({persisted:true});assert.equal(f.E.newProject.disabled,true);f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,2);resolve();await pending;assert.equal(f.E.newProject.disabled,false);assert.equal(f.E.editable.disabled,false);assert.match(f.E.audioProgress.textContent,/0 \/ 2/);f.E.newProject.onclick();assert.equal(f.E.sceneCards.children.length,0)});
 await test('空の新規作成は確認不要で取消履歴も復活しない',()=>{const f=fixture();f.E.newProject.onclick();assert.equal(f.state.confirmationCount,0);assert.equal(f.E.undo.disabled,true);f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,0);assert.equal(f.E.sourceWorkspace.hidden,true)});
 await test('画像生成中は移動・新規作成を拒否し取消後も元の構成を保持',async()=>{const f=fixture();await f.source();await f.apply();const title=f.E.title.value,pending=f.E.storyboard.onclick();assert.equal(f.E.editable.disabled,true);f.step(2);assert.deepEqual(f.active(),[1]);f.E.newProject.onclick();assert.equal(f.E.title.value,title);f.E.cancel.onclick();await pending;assert.equal(f.E.downloads.children.length,0);assert.equal(f.E.title.value,title);assert.equal(f.E.sceneCards.children.length,2);assert.equal(f.E.editable.disabled,false);f.E.newProject.onclick();f.E.undo.onclick();assert.equal(f.E.sceneCards.children.length,0)});
 await test('ファイル選択ラベル・工程所属・初期hidden属性が静的HTMLに存在',()=>{const f=fixture();for(const id of ['sourceFile','projectFile','audioFiles'])assert.match(markup,new RegExp('for="'+id+'"'));assert.equal(f.E.scenePanel.parentElement.id,'step2');assert.equal(f.E.script.parentElement.parentElement.parentElement.id,'step3');for(const id of ['sourceWorkspace','sourcePreparation','regionPanel','step2','step3','step4'])assert.match(markup,new RegExp('id="'+id+'"[^>]* hidden'));assert.match(markup,/自動保存はありません/);assert.doesNotMatch(markup,/保存済み/)});
 console.log(count+' workflow model tests passed. Visual layout, real dialogs, and browser export remain unverified.');
})().catch(e=>{console.error(e.message+'\n'+e.stack.split('\n').slice(1,4).join('\n'));process.exitCode=1});
